/* 🤖 this file was generated by svg-to-ts*/
export const viArrowDownToLine: {
  name: 'arrow_down_to_line';
  data: string;
} = {
  name: 'arrow_down_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path d="M8.75 1a.75.75 0 00-1.5 0v9.19L4.53 7.47a.75.75 0 00-1.06 1.06l3.823 3.824a1 1 0 001.414 0L12.53 8.53a.75.75 0 00-1.06-1.06l-2.72 2.72V1zM2 15.25a.75.75 0 01.75-.75h10.5a.75.75 0 010 1.5H2.75a.75.75 0 01-.75-.75z"/></svg>`
};
export const viArrowDown: {
  name: 'arrow_down';
  data: string;
} = {
  name: 'arrow_down',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 .25a.75.75 0 01.75.75h-1.5A.75.75 0 018 .25zm.75 12.94V1h-1.5v12.19L3.032 8.97H3.03a.75.75 0 00-1.061 1.06l5.323 5.323a1 1 0 001.414 0l5.317-5.318.004-.003.001-.001v-.001a.75.75 0 00-1.06-1.061L8.75 13.19z"/></svg>`
};
export const viArrowLeft: {
  name: 'arrow_left';
  data: string;
} = {
  name: 'arrow_left',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M15.75 8a.75.75 0 01-.75.75v-1.5a.75.75 0 01.75.75zm-12.94.75H15v-1.5H2.81l4.22-4.218V3.03a.75.75 0 00-1.06-1.06L.646 7.294a1 1 0 000 1.414l5.318 5.317.003.004.001.001h.001a.75.75 0 001.061-1.06L2.81 8.75z"/></svg>`
};
export const viArrowRightFromBracket: {
  name: 'arrow_right_from_bracket';
  data: string;
} = {
  name: 'arrow_right_from_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path d="M5.25 12.5H2.5a1 1 0 01-1-1v-7a1 1 0 011-1h2.75a.75.75 0 000-1.5H2a2 2 0 00-2 2v8a2 2 0 002 2h3.25a.75.75 0 000-1.5z"/><path d="M11.03 3.47a.75.75 0 10-1.06 1.06l2.72 2.72H6a.75.75 0 000 1.5h6.69l-2.72 2.72a.75.75 0 101.06 1.06l3.824-3.823a1 1 0 000-1.414L11.03 3.47z"/></svg>`
};
export const viArrowRightToBracket: {
  name: 'arrow_right_to_bracket';
  data: string;
} = {
  name: 'arrow_right_to_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path d="M10.75 3.5h2.75a1 1 0 011 1v7a1 1 0 01-1 1h-2.75a.75.75 0 000 1.5H14a2 2 0 002-2V4a2 2 0 00-2-2h-3.25a.75.75 0 000 1.5z"/><path d="M6.03 3.47a.75.75 0 00-1.06 1.06l2.72 2.72H1a.75.75 0 000 1.5h6.69l-2.72 2.72a.75.75 0 101.06 1.06l3.824-3.823a1 1 0 000-1.414L6.03 3.47z"/></svg>`
};
export const viArrowRight: {
  name: 'arrow_right';
  data: string;
} = {
  name: 'arrow_right',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M.25 8A.75.75 0 011 7.25v1.5A.75.75 0 01.25 8zm12.94-.75H1v1.5h12.19l-4.22 4.218v.001a.75.75 0 001.06 1.061l5.323-5.323a1 1 0 000-1.414l-5.318-5.317-.003-.004-.001-.001h-.001A.75.75 0 008.97 3.03l4.22 4.219z"/></svg>`
};
export const viArrowUp: {
  name: 'arrow_up';
  data: string;
} = {
  name: 'arrow_up',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 15.75a.75.75 0 01-.75-.75h1.5a.75.75 0 01-.75.75zM7.25 2.81V15h1.5V2.81l4.218 4.219h.001a.75.75 0 001.061-1.06L8.706.646a1 1 0 00-1.414 0L1.976 5.964l-.004.003-.001.001v.001A.75.75 0 003.03 7.03l4.22-4.22z"/></svg>`
};
export const viBook: {
  name: 'book';
  data: string;
} = {
  name: 'book',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path d="M10.25 4.5h-4.5a.75.75 0 010-1.5h4.5a.75.75 0 010 1.5z"/><path fill-rule="evenodd" d="M13 13a1 1 0 001-1V1a1 1 0 00-1-1H4a2 2 0 00-2 2v12a2 2 0 002 2h9.25a.75.75 0 000-1.5H13V13zm-.5-11a.5.5 0 00-.5-.5H4a.5.5 0 00-.5.5v9.628c.235-.083.487-.128.75-.128H12a.5.5 0 00.5-.5V2zm-1 11H4.25a.75.75 0 000 1.5h7.25V13z"/></svg>`
};
export const viHome: {
  name: 'home';
  data: string;
} = {
  name: 'home',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.813 8.252a.75.75 0 11-1.06-1.06L7.292.65a1 1 0 011.414 0l6.54 6.54a.75.75 0 01-1.06 1.061L14 8.065V14a2 2 0 01-2 2H4a2 2 0 01-2-2V8.065l-.187.187zM3.5 6.565V14a.5.5 0 00.5.5h8a.5.5 0 00.5-.5V6.565L8 2.065l-4.5 4.5z"/></svg>`
};
export const viImage: {
  name: 'image';
  data: string;
} = {
  name: 'image',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path d="M11 6a1 1 0 100-2 1 1 0 000 2z"/><path fill-rule="evenodd" d="M1 13a2 2 0 002 2h10a2 2 0 002-2V3a2 2 0 00-2-2H3a2 2 0 00-2 2v10zm12 .5h-.44L7.365 8.303a2.75 2.75 0 00-3.772-.11l-1.092.97V3a.5.5 0 01.5-.5h10a.5.5 0 01.5.5v10a.5.5 0 01-.5.5zM4.589 9.313L2.5 11.17V13a.5.5 0 00.5.5h7.44L6.302 9.364a1.25 1.25 0 00-1.714-.05z"/></svg>`
};
export const viXMark: {
  name: 'x_mark';
  data: string;
} = {
  name: 'x_mark',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M6.94 8L3.5 4.56A.75.75 0 014.56 3.5L8 6.94l3.44-3.44a.75.75 0 111.06 1.06L9.06 8l3.44 3.44a.75.75 0 01-1.06 1.06L8 9.06 4.56 12.5a.75.75 0 01-1.06-1.06L6.94 8z"/></svg>`
};
export type Valkyrie =
  | 'arrow_down_to_line'
  | 'arrow_down'
  | 'arrow_left'
  | 'arrow_right_from_bracket'
  | 'arrow_right_to_bracket'
  | 'arrow_right'
  | 'arrow_up'
  | 'book'
  | 'home'
  | 'image'
  | 'x_mark';
export interface ValkyrieIcon {
  name: Valkyrie;
  data: string;
}
export type ValkyrieIconNameSubset<
  T extends Readonly<ValkyrieIcon[]>
> = T[number]['name'];
