import Release from "./_Release";

export default function Changelog() {
  return (
    <div className="flex flex-col gap-4">
      <Release
        name="Valkyrie 1.0.0"
        version="1.0.0"
        date="7 July 2026"
        added={[
          "Fully redesigned icons based on Amicons.",
          "Adds the React `Valkyrie` component.",
          "Valkyrie is now available as both a CJS and ESM package.",
          "Adds new animations like fade, beat, pulse, and bounce to our default CSS.",
          "When the `Valkyrie` component isn't passed an icon, or the icon isn't valid, it will now show the `viCircleQuestion` icon. The `fade` property will be enabled to draw attention to it.",
        ]}
        changed={[
          "Improved tooling for builds.",
          "Renames the `ValkyrieIcon` type to `IValkyrie`.",
          "CSS transitions are now inherited from the parent element.",
          "Rotate now allows you to set any numeric value rather than just `0`, `90`, `180`, or `270`.",
          "Valkyrie no longer depends on any other package.",
          "Major enhancements to our build process and library generation. We now include source maps.",
        ]}
        docs={[
          "Introduces a brand new documentation website with improved icon previews, component documentation with interactive playground, this changelog, and much more. And best of all; it's now available online instead of needing to be compiled by you.",
        ]}
        removed={["Removes the included CSS and font files."]}
        newIcons={[
          "align-center",
          "align-content-center",
          "align-content-end",
          "align-content-start",
          "align-justify",
          "align-left",
          "align-right",
          "angles-x",
          "apple",
          "arrow-down-arrow-up",
          "arrow-down-from-cloud",
          "arrow-left-arrow-right",
          "arrow-right-from-file",
          "arrow-right-to-bracket-clock",
          "arrow-right-to-file",
          "arrow-up-right-from-square",
          "arrow-up-to-cloud",
          "arrows-up-right-and-down-left-from-center",
          "arrows-up-right-and-down-left-to-center",
          "bars-uneven",
          "bel",
          "broom",
          "burger-glass",
          "calendar-arrow-to-day",
          "calendar-clock",
          "calendar-day",
          "calendar-range-clock",
          "calendar-range",
          "calendar-week",
          "car-side",
          "chalkboard-person",
          "check",
          "circle-check",
          "circle-dashed",
          "circle-half-inner",
          "circle-half",
          "cloud-softphone",
          "coin",
          "command",
          "compare",
          "cursor",
          "diagram",
          "diamonds",
          "dice-five",
          "dice-four",
          "dice-one",
          "dice-six",
          "dice-three",
          "dice-two",
          "dice",
          "dollar",
          "door",
          "ellipsis-v",
          "export",
          "fanvil",
          "file-audio",
          "file-excel",
          "file-powerpoint",
          "file-text",
          "file-word",
          "file-zip",
          "flask",
          "folder-image",
          "folder-min",
          "folder-open",
          "folder-plus",
          "glass",
          "grip-dots-v",
          "grip-dots",
          "horizontal-line",
          "id-card-slash",
          "input",
          "key",
          "keyboard-brightness-high",
          "keyboard-brightness-low",
          "keyboard",
          "life-ring",
          "list-bar-chart",
          "list-chekcs-xmark",
          "magnifying-glass-min",
          "magnifying-glass-plus",
          "microphone-slash",
          "min",
          "moped",
          "music-pause",
          "next",
          "order-alphabetical-asc",
          "order-alphabetical-desc",
          "order-numerical-asc",
          "order-numerical-desc",
          "pager",
          "password",
          "pen-to-square",
          "people-xmark",
          "person-xmark",
          "phone-xmark",
          "plate-utensils",
          "pound",
          "previous",
          "react",
          "receipt",
          "record-stop",
          "record",
          "rectangle-p",
          "share",
          "shopping-cart",
          "sidebar-left",
          "sidebar-right",
          "signal-fair",
          "signal-good",
          "signal-moderate",
          "signal-slash",
          "signal-strong",
          "signal-weak",
          "sparkle",
          "sparkles",
          "speaker-grill",
          "spinner",
          "square-check",
          "subscript",
          "superscript",
          "table-cell-merge",
          "table-column-insert-left",
          "table-column-insert-right",
          "table-column-min",
          "table-header-cell",
          "table-header-column",
          "table-header-row",
          "table-min",
          "table-row-insert-bottom",
          "table-row-insert-top",
          "table-row-min",
          "tag-gear",
          "tag-plus",
          "teams",
          "toggle-off",
          "toggle-on",
          "translate",
          "wallet",
          "windows",
          "yealink",
        ]}
        updatedIcons={[
          "arrow-down-to-line",
          "arrow-left-from-bracket",
          "devices",
          "facebook-messenger",
          "gauge",
          "github",
          "google-play",
          "message-pen",
          "safari",
          "shield-plus",
          "shield-xmark",
          "triangle-exclamation",
        ]}
        renamedIcons={[
          { old: "arrow-right-ban", new: "arrow-right-prohibited" },
          { old: "ban", new: "prohibited" },
          { old: "circle-user", new: "circle-person" },
          { old: "clear-formatting", new: "a-gum" },
          { old: "clear-node", new: "square-gum" },
          { old: "ellipsis", new: "ellipsis-h" },
          { old: "film", new: "filmstrip" },
          { old: "grip-dots", new: "grip-dots-h" },
          { old: "horizontal-rule", new: "line" },
          { old: "link-slash", new: "chain-slash" },
          { old: "link", new: "chain" },
          { old: "list-check", new: "list-checks" },
          { old: "list-ol-clock", new: "list-ordered-clock" },
          { old: "list-ol", new: "list-ordered" },
          { old: "logs", new: "files-list" },
          { old: "paper-plane-top", new: "paper-plane" },
          { old: "phone-arrow-down-left-ban", new: "phone-arrow-down-left-prohibited" },
          { old: "phone-arrow-up-right-ban", new: "phone-arrow-up-right-prohibited" },
          { old: "pin-slash", new: "thumbtack-slash" },
          { old: "pin", new: "thumbtack" },
          { old: "repeat-1", new: "repeat-once" },
          { old: "smartphone-arrow-right", new: "arrow-right-from-smartphone" },
          { old: "smartphone-divert", new: "smartphone-arrow-right" },
          { old: "square-p", new: "rectangle-p" },
          { old: "unlock", new: "lock-open" },
          { old: "user-clock", new: "person-clock" },
          { old: "user-gear", new: "person-gear" },
          { old: "user-headset", new: "person-headset" },
          { old: "user-list", new: "person-list" },
          { old: "user-lock", new: "person-lock" },
          { old: "user-plus", new: "person-plus" },
          { old: "user", new: "person" },
          { old: "users", new: "people" },
          { old: "volumne-none", new: "volume-slash" },
        ]}
      />
    </div>
  );
}
