import Release from "./_Release";

export default function Changelog() {
  return (
    <div className="flex flex-col gap-4">
      <Release
        name="Valkyrie 1.0 Release Candidate 1"
        version="1.0.0-rc.1"
        date="April 2026"
        docs={[
          "The documentation has been rebuilt with Tailwind and Base UI.",
          "The search function can now properly look for tags.",
          "Major improvements to our documentation, including simpeler changelog markup.",
        ]}
      />
      <Release
        name="Valkyrie 1.0 beta"
        version="1.0.0-beta.6"
        date="11 March 2026"
        added={[
          "Valkyrie is now available as both a CJS and ESM package.",
          "Adds the bounce animation to our default style, and added the `bounce` prop to our React component.",
          "When the `Valkyrie` component isn't passed an icon, or the icon isn't valid, it will now show the `viCircleQuestion` icon. The `fade` property will be enabled to draw attention to it.",
        ]}
        changed={[
          "The `ValkyrieIcon` component has been renamed to `Valkyrie`.",
          "Rotate now allows you to set any numeric value rather than just `0`, `90`, `180`, or `270`.",
          "Valkyrie now only has 1 dependency as we've dropped `@emotion/css` and `html-react-parser`.",
          "Major enhancements to our build process and library generation. We now include source maps.",
        ]}
        fixed={[
          "Fixes the ESM export missing file extensions.",
          "Fixes the SVG and export for `fingerprint`, `record-stop`, `safari`, `signal-strong`, and `triangle-exclamation` containing the icon twice.",
          "Fixes a bug where `rotate` would not correctly apply the animation styling.",
          "Fixes a bug where markdown generation would report a successful run before finishing.",
        ]}
        docs={[
          "The category filter now keeps showing empty categories for easier navigation.",
          "Various categories have been updated and categories have been regrouped to make more sense.",
          "Major improvements to our documentation, including simpeler changelog markup.",
        ]}
        newIcons={[
          "arrows-up-right-and-down-left-from-center",
          "arrows-up-right-and-down-left-to-center",
          "calendar-arrow-to-day",
          "cursor",
          "diamonds",
          "id-card-slash",
          "input",
          "square-check",
        ]}
        updatedIcons={[
          "arrow-down-to-line",
          "arrow-left-from-bracket",
          "arrow-up-right-from-square",
          "devices",
          "fanvil",
          "fingerprint",
          "gauge",
          "keyboard",
          "message-pen",
          "record-stop",
          "safari",
          "signal-strong",
          "teams",
          "triangle-exclamation",
          "yealink",
        ]}
      />
      <Release
        name="Valkyrie 1.0 alpha"
        version="1.0.0-alpha.57"
        date="19 May 2025"
        added={[
          "Fully redesigned icons based on Amicons.",
          "Adds the React `ValkyrieIcon` component.",
          "Adds new animations like fade, beat and pulse to our default CSS.",
          "Introduces a brand new documentation website with improved icon previews, component documentation with interactive playground, this changelog, and much more. And best of all; it's now available online instead of needing to be compiled by you.",
        ]}
        changed={[
          "Improved tooling for builds.",
          "Renames the `ValkyrieIcon` type to `IValkyrie`.",
          "CSS transitions are now inherited from the parent element.",
        ]}
        removed={["Removes the included CSS and font files."]}
        newIcons={[
          "align-center",
          "align-content-center",
          "align-content-end",
          "align-content-start",
          "align-justify",
          "align-left",
          "align-right",
          "angles-x",
          "apple",
          "arrow-down-arrow-up",
          "arrow-down-from-cloud",
          "arrow-left-arrow-right",
          "arrow-right-from-file",
          "arrow-right-to-bracket-clock",
          "arrow-right-to-file",
          "arrow-up-right-from-square",
          "arrow-up-to-cloud",
          "bars-uneven",
          "bel",
          "broom",
          "burger-glass",
          "calendar-clock",
          "calendar-day",
          "calendar-range-clock",
          "calendar-range",
          "calendar-week",
          "car-side",
          "chalkboard-person",
          "check",
          "circle-check",
          "circle-dashed",
          "circle-half-inner",
          "circle-half",
          "cloud-softphone",
          "command",
          "compare",
          "diagram",
          "dice-five",
          "dice-four",
          "dice-one",
          "dice-six",
          "dice-three",
          "dice-two",
          "dice",
          "door",
          "ellipsis-v",
          "export",
          "fanvil",
          "file-audio",
          "file-excel",
          "file-powerpoint",
          "file-text",
          "file-word",
          "file-zip",
          "flask",
          "folder-image",
          "folder-min",
          "folder-open",
          "folder-plus",
          "glass",
          "grip-dots-v",
          "grip-dots",
          "horizontal-line",
          "key",
          "keyboard-brightness-high",
          "keyboard-brightness-low",
          "keyboard",
          "life-ring",
          "list-bar-chart",
          "list-chekcs-xmark",
          "magnifying-glass-min",
          "magnifying-glass-plus",
          "microphone-slash",
          "min",
          "moped",
          "music-pause",
          "next",
          "order-alphabetical-asc",
          "order-alphabetical-desc",
          "order-numerical-asc",
          "order-numerical-desc",
          "pager",
          "password",
          "people-xmark",
          "person-xmark",
          "phone-xmark",
          "plate-utensils",
          "previous",
          "react",
          "receipt",
          "record-stop",
          "record",
          "rectangle-p",
          "share",
          "shopping-cart",
          "sidebar-left",
          "sidebar-right",
          "signal-fair",
          "signal-good",
          "signal-moderate",
          "signal-slash",
          "signal-strong",
          "signal-weak",
          "speaker-grill",
          "spinner",
          "subscript",
          "superscript",
          "table-cell-merge",
          "table-column-insert-left",
          "table-column-insert-right",
          "table-column-min",
          "table-header-cell",
          "table-header-column",
          "table-header-row",
          "table-min",
          "table-row-insert-bottom",
          "table-row-insert-top",
          "table-row-min",
          "tag-gear",
          "tag-plus",
          "teams",
          "toggle-off",
          "toggle-on",
          "translate",
          "wallet",
          "windows",
          "yealink",
        ]}
        renamedIcons={[
          { old: "pin", new: "thumbtack" },
          { old: "pin-slash", new: "thumbtack-slash" },
          { old: "grip-dots", new: "grip-dots-h" },
          { old: "ellipsis", new: "ellipsis-h" },
          { old: "smartphone-arrow-right", new: "arrow-right-from-smartphone" },
          { old: "square-p", new: "rectangle-p" },
          { old: "circle-user", new: "circle-person" },
          { old: "arrow-right-ban", new: "arrow-right-prohibited" },
          { old: "ban", new: "prohibited" },
          { old: "clear-formatting", new: "a-gum" },
          { old: "clear-node", new: "square-gum" },
          { old: "film", new: "filmstrip" },
          { old: "horizontal-rule", new: "line" },
          { old: "link", new: "chain" },
          { old: "link-slash", new: "chain-slash" },
          { old: "list-check", new: "list-checks" },
          { old: "list-ol", new: "list-ordered" },
          { old: "list-ol-clock", new: "list-ordered-clock" },
          { old: "logs", new: "files-list" },
          { old: "paper-plane-top", new: "paper-plane" },
          { old: "phone-arrow-down-left-ban", new: "phone-arrow-down-left-prohibited" },
          { old: "phone-arrow-up-right-ban", new: "phone-arrow-up-right-prohibited" },
          { old: "repeat-1", new: "repeat-once" },
          { old: "smartphone-divert", new: "smartphone-arrow-right" },
          { old: "unlock", new: "lock-open" },
          { old: "users", new: "people" },
          { old: "user", new: "person" },
          { old: "user-clock", new: "person-clock" },
          { old: "user-gear", new: "person-gear" },
          { old: "user-headset", new: "person-headset" },
          { old: "user-list", new: "person-list" },
          { old: "user-lock", new: "person-lock" },
          { old: "user-plus", new: "person-plus" },
          { old: "volumne-none", new: "volume-slash" },
        ]}
      />
    </div>
  );
}
