/* 🤖 this file was generated by svg-to-ts*/
export const viAngleDown: {
  name: 'angle_down';
  data: string;
} = {
  name: 'angle_down',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4.5 6.56A.75.75 0 015.56 5.5l4.26 4.26c.1.1.26.1.36 0l4.26-4.26a.75.75 0 011.06 1.06l-4.8 4.8a1 1 0 01-1.4 0l-4.8-4.8z"/></svg>`
};
export const viAngleLeft: {
  name: 'angle_left';
  data: string;
} = {
  name: 'angle_left',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.47 2.53a.75.75 0 111.06 1.06L8.27 7.85c-.1.1-.1.26 0 .36l4.26 4.26a.75.75 0 11-1.06 1.06l-4.8-4.8a1 1 0 010-1.4l4.8-4.8z"/></svg>`
};
export const viAngleRight: {
  name: 'angle_right';
  data: string;
} = {
  name: 'angle_right',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8.53 13.53a.75.75 0 01-1.06-1.06l4.26-4.26c.1-.1.1-.26 0-.36L7.47 3.6a.75.75 0 111.06-1.06l4.8 4.8a1 1 0 010 1.4l-4.8 4.8z"/></svg>`
};
export const viAngleUp: {
  name: 'angle_up';
  data: string;
} = {
  name: 'angle_up',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M15.5 9.5a.75.75 0 01-1.06 1.06L10.18 6.3a.25.25 0 00-.36 0l-4.26 4.26A.75.75 0 114.5 9.5l4.8-4.8a1 1 0 011.4 0l4.8 4.8z"/></svg>`
};
export const viAppleAppStore: {
  name: 'apple_app_store';
  data: string;
} = {
  name: 'apple_app_store',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M15.5 1h-11C3.67 1 3 1.67 3 2.5v11c0 .83.67 1.5 1.5 1.5h11c.83 0 1.5-.67 1.5-1.5v-11c0-.83-.67-1.5-1.5-1.5zM6.97 12.02a.62.62 0 11-1.08-.63l.44-.77c.5-.15.92-.04 1.24.36l-.6 1.04zm4.34-1.69H5.62A.63.63 0 015 9.71c0-.35.28-.63.63-.63h1.59l2.04-3.54-.64-1.1a.63.63 0 01.23-.86c.3-.17.68-.06.85.23l.28.48.28-.48a.62.62 0 111.08.63L8.66 9.08h1.94c.63 0 .98.74.7 1.25zm3.06 0h-.9l.61 1.06a.63.63 0 01-1.08.63l-2.31-4c-.52-.91-.15-1.82.22-2.13l1.84 3.2h1.63c.34 0 .62.27.62.62 0 .34-.28.62-.63.62z"/></svg>`
};
export const viArrowDownToLine: {
  name: 'arrow_down_to_line';
  data: string;
} = {
  name: 'arrow_down_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.25 1.75l-.03 7.97-3.19-3.19a.75.75 0 00-1.06 1.06l4.3 4.3a1 1 0 001.4 0l4.3-4.3a.75.75 0 10-1.06-1.06l-3.19 3.19.03-7.97a.75.75 0 00-1.5 0zM4.75 13.5a.75.75 0 000 1.5h10.5a.75.75 0 000-1.5H4.75z"/></svg>`
};
export const viArrowDown: {
  name: 'arrow_down';
  data: string;
} = {
  name: 'arrow_down',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.25 12.19V1.75a.75.75 0 011.5 0v10.44l3.69-3.69a.75.75 0 011.06 1.06l-4.8 4.8a1 1 0 01-1.4 0l-4.8-4.8A.75.75 0 015.56 8.5l3.69 3.69z"/></svg>`
};
export const viArrowLeftFromBracket: {
  name: 'arrow_left_from_bracket';
  data: string;
} = {
  name: 'arrow_left_from_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M12 14.25c0 .41.34.75.75.75H15a3 3 0 003-3V4a3 3 0 00-3-3h-2.25a.75.75 0 000 1.5H15c.83 0 1.5.67 1.5 1.5v8c0 .83-.67 1.5-1.5 1.5h-2.25a.75.75 0 00-.75.75z"/><path fill-rule="evenodd" d="M7.2 12.5c-.3.3-.77.3-1.06 0l-3.8-3.8a1 1 0 010-1.4l3.8-3.8A.75.75 0 017.2 4.56L4.51 7.25h7.44a.75.75 0 010 1.5H4.51l2.69 2.69c.3.3.3.77 0 1.06z"/></svg>`
};
export const viArrowLeftToBracket: {
  name: 'arrow_left_to_bracket';
  data: string;
} = {
  name: 'arrow_left_to_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8 1.75A.75.75 0 007.25 1H5a3 3 0 00-3 3v8a3 3 0 003 3h2.25a.75.75 0 000-1.5H5A1.5 1.5 0 013.5 12V4c0-.83.67-1.5 1.5-1.5h2.25c.41 0 .75-.34.75-.75z"/><path fill-rule="evenodd" d="M12.5 12.5c-.3.3-.77.3-1.06 0l-3.8-3.8a1 1 0 010-1.4l3.8-3.8a.75.75 0 011.06 1.06L9.81 7.25h7.44a.75.75 0 010 1.5H9.81l2.69 2.69c.3.3.3.77 0 1.06z"/></svg>`
};
export const viArrowLeftToLine: {
  name: 'arrow_left_to_line';
  data: string;
} = {
  name: 'arrow_left_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4.5 2.75a.75.75 0 00-1.5 0v10.5a.75.75 0 001.5 0V2.75zm11.75 4.5l-7.97-.03 3.19-3.19a.75.75 0 10-1.06-1.06l-4.3 4.3a1 1 0 000 1.4l4.3 4.3a.75.75 0 001.06-1.06L8.28 8.72l7.97.03a.75.75 0 000-1.5z"/></svg>`
};
export const viArrowLeft: {
  name: 'arrow_left';
  data: string;
} = {
  name: 'arrow_left',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M5.84 7.28h10.44a.75.75 0 010 1.5H5.84l3.69 3.69a.75.75 0 11-1.06 1.06l-4.8-4.8a1 1 0 010-1.4l4.8-4.8a.75.75 0 111.06 1.06L5.84 7.28z"/></svg>`
};
export const viArrowRightFromBracket: {
  name: 'arrow_right_from_bracket';
  data: string;
} = {
  name: 'arrow_right_from_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8 1.75A.75.75 0 007.25 1H5a3 3 0 00-3 3v8a3 3 0 003 3h2.25a.75.75 0 000-1.5H5A1.5 1.5 0 013.5 12V4c0-.83.67-1.5 1.5-1.5h2.25c.41 0 .75-.34.75-.75z"/><path fill-rule="evenodd" d="M12.8 3.5c.3-.3.77-.3 1.06 0l3.8 3.8a1 1 0 010 1.4l-3.8 3.8a.75.75 0 01-1.06-1.06l2.69-2.69H8.05a.75.75 0 010-1.5h7.44L12.8 4.56a.75.75 0 010-1.06z"/></svg>`
};
export const viArrowRightToBracket: {
  name: 'arrow_right_to_bracket';
  data: string;
} = {
  name: 'arrow_right_to_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M12 14.25c0 .41.34.75.75.75H15a3 3 0 003-3V4a3 3 0 00-3-3h-2.25a.75.75 0 000 1.5H15c.83 0 1.5.67 1.5 1.5v8c0 .83-.67 1.5-1.5 1.5h-2.25a.75.75 0 00-.75.75z"/><path fill-rule="evenodd" d="M7.5 3.5c.3-.3.77-.3 1.06 0l3.8 3.8a1 1 0 010 1.4l-3.8 3.8a.75.75 0 11-1.06-1.06l2.69-2.69H2.75a.75.75 0 110-1.5h7.44L7.5 4.56a.75.75 0 010-1.06z"/></svg>`
};
export const viArrowRightToLine: {
  name: 'arrow_right_to_line';
  data: string;
} = {
  name: 'arrow_right_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M15.5 13.25a.75.75 0 001.5 0V2.75a.75.75 0 00-1.5 0v10.5zM3.75 8.75l7.97.03-3.19 3.19a.75.75 0 101.06 1.06l4.3-4.3a1 1 0 000-1.4l-4.3-4.3a.75.75 0 00-1.06 1.06l3.19 3.19-7.97-.03a.75.75 0 100 1.5z"/></svg>`
};
export const viArrowRight: {
  name: 'arrow_right';
  data: string;
} = {
  name: 'arrow_right',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M14.16 8.78H3.72a.75.75 0 010-1.5h10.44l-3.69-3.69a.75.75 0 011.06-1.06l4.8 4.8a1 1 0 010 1.4l-4.8 4.8a.75.75 0 11-1.06-1.06l3.69-3.69z"/></svg>`
};
export const viArrowUpToLine: {
  name: 'arrow_up_to_line';
  data: string;
} = {
  name: 'arrow_up_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M15.25 2.5a.75.75 0 000-1.5H4.75a.75.75 0 000 1.5h10.5zm-4.5 11.75l.03-7.97 3.19 3.19a.75.75 0 101.06-1.06l-4.3-4.3a1 1 0 00-1.4 0l-4.3 4.3a.75.75 0 001.06 1.06l3.19-3.19-.03 7.97a.75.75 0 001.5 0z"/></svg>`
};
export const viArrowUp: {
  name: 'arrow_up';
  data: string;
} = {
  name: 'arrow_up',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10.75 3.87v10.44a.75.75 0 01-1.5 0V3.87l-3.69 3.7A.75.75 0 014.5 6.5l4.8-4.8a1 1 0 011.4 0l4.8 4.8a.75.75 0 11-1.06 1.06l-3.69-3.69z"/></svg>`
};
export const viBars: {
  name: 'bars';
  data: string;
} = {
  name: 'bars',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M3.75 2a.75.75 0 000 1.5h12.5a.75.75 0 000-1.5H3.75zM3 8c0-.41.34-.75.75-.75h12.5a.75.75 0 010 1.5H3.75A.75.75 0 013 8zm0 5.25c0-.41.34-.75.75-.75h12.5a.75.75 0 010 1.5H3.75a.75.75 0 01-.75-.75z"/></svg>`
};
export const viBlf: {
  name: 'blf';
  data: string;
} = {
  name: 'blf',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M19.67 6.1a5.5 5.5 0 00-5.17-3.6h-9a5.5 5.5 0 100 11h9a5.5 5.5 0 005.17-7.4zM5.5 4h9a4 4 0 013.46 2H14a2 2 0 100 4h3.96a4 4 0 01-3.46 2h-9a4 4 0 010-8zm13 4c0 .17-.01.34-.03.5H14a.5.5 0 010-1h4.47c.02.16.03.33.03.5z"/></svg>`
};
export const viBook: {
  name: 'book';
  data: string;
} = {
  name: 'book',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.25 4.5h-4.5a.75.75 0 010-1.5h4.5a.75.75 0 010 1.5z"/><path fill-rule="evenodd" d="M15 13a1 1 0 001-1V1a1 1 0 00-1-1H6a2 2 0 00-2 2v12c0 1.1.9 2 2 2h9.25a.75.75 0 000-1.5H15V13zm-.5-11v9a.5.5 0 01-.5.5H6.25c-.26 0-.52.05-.75.13V2c0-.28.22-.5.5-.5h8c.28 0 .5.22.5.5zm-1 11v1.5H6.25a.75.75 0 010-1.5h7.25z"/></svg>`
};
export const viBoxFull: {
  name: 'box_full';
  data: string;
} = {
  name: 'box_full',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M16.64 4.31l-1.7.3.1-.06-1.5-2.6-2.59 1.5.97 1.68-1.57.28-.42-.72c-.05.25-.13.5-.23.73l-1.56-.27a2 2 0 10-3.57-.62L3 4.24V4a3.5 3.5 0 016.65-1.52 1 1 0 01.12-.08l3.46-2a1 1 0 011.37.37l2 3.46a1 1 0 01.04.08zM10 7L1.9 5.57a.5.5 0 00-.55.3L.7 7.52a.5.5 0 00.3.66l6.61 2.2a.5.5 0 00.6-.23L10 7zm0 0l1.8 3.14c.11.21.36.3.59.23l6.6-2.2a.5.5 0 00.31-.66l-.65-1.63a.5.5 0 00-.55-.3L10 7z"/><path d="M10 9.5c.41 0 .75.34.75.75v3.94l5.75-1.8v-1.8l1.5-.5v2.67a1 1 0 01-.7.96l-6.7 2.1a2 2 0 01-1.2 0l-6.7-2.1a1 1 0 01-.7-.96V10.1l1.5.5v1.8l5.75 1.8v-3.94c0-.41.34-.75.75-.75z"/></svg>`
};
export const viBuilding: {
  name: 'building';
  data: string;
} = {
  name: 'building',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M5.5 2.75c0-.69.56-1.25 1.25-1.25h6.5c.69 0 1.25.56 1.25 1.25V16H16V2.75A2.75 2.75 0 0013.25 0h-6.5A2.75 2.75 0 004 2.75V16h1.5V2.75z"/><path d="M8.5 16v-4a1 1 0 011-1h1a1 1 0 011 1v4h-3zM7 3.5c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5v-1zm4.5-.5a.5.5 0 00-.5.5v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5h-1zM7 7.5c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5v-1zm4.5-.5a.5.5 0 00-.5.5v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5h-1z"/></svg>`
};
export const viCalendarHolidays: {
  name: 'calendar_holidays';
  data: string;
} = {
  name: 'calendar_holidays',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11.3 9h-.05a.75.75 0 010-1.5h.05a.2.2 0 00.2-.2v-.05a.75.75 0 011.5 0v.05c0 .11.09.2.2.2h.05a.75.75 0 010 1.5h-.05a.2.2 0 00-.2.2v.05a.75.75 0 01-1.5 0V9.2a.2.2 0 00-.2-.2zm-4.55 3h.05c.11 0 .2.09.2.2v.05a.75.75 0 001.5 0v-.05c0-.11.09-.2.2-.2h.05a.75.75 0 000-1.5H8.7a.2.2 0 01-.2-.2v-.05a.75.75 0 00-1.5 0v.05a.2.2 0 01-.2.2h-.05a.75.75 0 000 1.5z"/><path fill-rule="evenodd" d="M6.75 0A.75.75 0 006 .75V2H5a2 2 0 00-2 2v10c0 1.1.9 2 2 2h10a2 2 0 002-2V4a2 2 0 00-2-2h-1V.75a.75.75 0 00-1.5 0V2h-5V.75A.75.75 0 006.75 0zM4.5 5h11v9a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V5z"/></svg>`
};
export const viCalendar: {
  name: 'calendar';
  data: string;
} = {
  name: 'calendar',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.75 0A.75.75 0 006 .75V2H5a2 2 0 00-2 2v10c0 1.1.9 2 2 2h10a2 2 0 002-2V4a2 2 0 00-2-2h-1V.75a.75.75 0 00-1.5 0V2h-5V.75A.75.75 0 006.75 0zM4.5 5h11v9a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V5z"/></svg>`
};
export const viCheck: {
  name: 'check';
  data: string;
} = {
  name: 'check',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M16.53 3.53c.3.3.3.77 0 1.06l-7.8 7.8a1 1 0 01-1.4 0l-3.8-3.8a.75.75 0 011.06-1.06l3.09 3.09c.2.2.5.2.7 0l7.09-7.09c.3-.3.77-.3 1.06 0z"/></svg>`
};
export const viCircleCheck: {
  name: 'circle_check';
  data: string;
} = {
  name: 'circle_check',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.44 5.5L9 8.94 7.56 7.5A.75.75 0 006.5 8.56l1.8 1.8a1 1 0 001.4 0l3.8-3.8a.75.75 0 10-1.06-1.06z"/><path fill-rule="evenodd" d="M18 8A8 8 0 112 8a8 8 0 0116 0zm-1.5 0a6.5 6.5 0 10-13 0 6.5 6.5 0 0013 0z"/></svg>`
};
export const viCircleDanger: {
  name: 'circle_danger';
  data: string;
} = {
  name: 'circle_danger',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M6.64 10.3L8.94 8l-2.3-2.3A.75.75 0 117.7 4.64l2.3 2.3 2.3-2.3a.75.75 0 111.06 1.06L11.06 8l2.3 2.3a.75.75 0 01-1.06 1.06L10 9.06l-2.3 2.3a.75.75 0 11-1.06-1.06z"/><path fill-rule="evenodd" d="M18 8A8 8 0 102 8a8 8 0 0016 0zm-1.5 0a6.5 6.5 0 11-13 0 6.5 6.5 0 0113 0z"/></svg>`
};
export const viCircleInfo: {
  name: 'circle_info';
  data: string;
} = {
  name: 'circle_info',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11.5 4.25a1.25 1.25 0 11-2.5 0 1.25 1.25 0 012.5 0zM11 8v3h.75a.75.75 0 010 1.5h-3a.75.75 0 010-1.5h.75V8.5h-.25a.75.75 0 010-1.5H10a1 1 0 011 1z"/><path fill-rule="evenodd" d="M10 16a8 8 0 100-16 8 8 0 000 16zm0-1.5a6.5 6.5 0 110-13 6.5 6.5 0 010 13z"/></svg>`
};
export const viCirclePlus: {
  name: 'circle_plus';
  data: string;
} = {
  name: 'circle_plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M6 7.25h3.25V4a.75.75 0 011.5 0v3.25H14a.75.75 0 010 1.5h-3.25V12a.75.75 0 01-1.5 0V8.75H6a.75.75 0 010-1.5z"/><path fill-rule="evenodd" d="M18 8A8 8 0 102 8a8 8 0 0016 0zm-1.5 0a6.5 6.5 0 11-13 0 6.5 6.5 0 0113 0z"/></svg>`
};
export const viCircleQuestion: {
  name: 'circle_question';
  data: string;
} = {
  name: 'circle_question',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M8.31 3.3A2.98 2.98 0 0110 2.74a3 3 0 011.69.54 2.6 2.6 0 011.06 2.21c0 1.3-.7 2.07-1.45 2.44-.19.1-.34.2-.44.32a.37.37 0 00-.11.24l-.03.78a.75.75 0 11-1.5-.06l.03-.72c0-1 .81-1.62 1.38-1.9.18-.09.33-.2.43-.36.1-.16.19-.39.19-.74 0-.56-.21-.83-.44-1-.26-.18-.6-.25-.81-.25-.21 0-.55.07-.81.26a.98.98 0 00-.26.27c-.22.35-.52.72-.93.72-.41 0-.76-.34-.67-.74a2.5 2.5 0 01.98-1.47zM10 13a1 1 0 100-2 1 1 0 000 2z"/><path fill-rule="evenodd" d="M10 16a8 8 0 100-16 8 8 0 000 16zm0-1.5a6.5 6.5 0 110-13 6.5 6.5 0 010 13z"/></svg>`
};
export const viCircleUser: {
  name: 'circle_user';
  data: string;
} = {
  name: 'circle_user',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 8.5A2.75 2.75 0 1010 3a2.75 2.75 0 000 5.5zM10 7a1.25 1.25 0 110-2.5A1.25 1.25 0 0110 7z"/><path fill-rule="evenodd" d="M16.25 13a8 8 0 10-1.05 1.09c.38-.33.73-.7 1.05-1.09zm-1.06-1.09a7.97 7.97 0 00-10.38 0 6.5 6.5 0 1110.38 0zM14.15 13a6.47 6.47 0 01-8.3 0 6.47 6.47 0 018.3 0z"/></svg>`
};
export const viCircleWarning: {
  name: 'circle_warning';
  data: string;
} = {
  name: 'circle_warning',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11 11.75a1 1 0 11-2 0 1 1 0 012 0zM10.75 9V4a.75.75 0 00-1.5 0v5a.75.75 0 001.5 0z"/><path fill-rule="evenodd" d="M10 16a8 8 0 110-16 8 8 0 010 16zm0-1.5a6.5 6.5 0 100-13 6.5 6.5 0 000 13z"/></svg>`
};
export const viClock: {
  name: 'clock';
  data: string;
} = {
  name: 'clock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M9.25 8V3.75a.75.75 0 011.5 0v3.94l1.43 1.43a.75.75 0 11-1.06 1.06L9.53 8.6a.76.76 0 01-.03-.03.75.75 0 01-.25-.56z"/><path fill-rule="evenodd" d="M10 16a8 8 0 100-16 8 8 0 000 16zm0-1.5a6.5 6.5 0 110-13 6.5 6.5 0 010 13z"/></svg>`
};
export const viCompass: {
  name: 'compass';
  data: string;
} = {
  name: 'compass',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.43 5.1l1.86 3.72c.2.38.5.7.9.9l3.71 1.85a.5.5 0 00.67-.67l-1.86-3.72a2 2 0 00-.9-.9L7.1 4.44a.5.5 0 00-.67.67zM11 8a1 1 0 11-2 0 1 1 0 012 0z"/><path fill-rule="evenodd" d="M18 8A8 8 0 112 8a8 8 0 0116 0zm-1.5 0a6.5 6.5 0 10-13 0 6.5 6.5 0 0013 0z"/></svg>`
};
export const viCopy: {
  name: 'copy';
  data: string;
} = {
  name: 'copy',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8 10V2c0-1.1.9-2 2-2h4.17a2 2 0 011.42.59L17.4 2.4a2 2 0 01.6 1.43V10a2 2 0 01-2 2h-6a2 2 0 01-2-2zm1.5 0c0 .28.22.5.5.5h6a.5.5 0 00.5-.5V4.75h-2.25a1 1 0 01-1-1V1.5H10a.5.5 0 00-.5.5v8zm5.25-8.13v1.38h1.38l-1.38-1.38z"/><path d="M6.5 4H4a2 2 0 00-2 2v8c0 1.1.9 2 2 2h6a2 2 0 002-2v-.5h-1.5v.5a.5.5 0 01-.5.5H4a.5.5 0 01-.5-.5V6c0-.28.22-.5.5-.5h2.5V4z"/></svg>`
};
export const viDashboard: {
  name: 'dashboard';
  data: string;
} = {
  name: 'dashboard',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4 1a1 1 0 00-1 1v4.25a1 1 0 001 1h4.25a1 1 0 001-1V2a1 1 0 00-1-1H4zm.5 1.5h3.25v3.25H4.5V2.5zM3 9.75a1 1 0 011-1h4.25a1 1 0 011 1V14a1 1 0 01-1 1H4a1 1 0 01-1-1V9.75zm1.5 3.75h3.25v-3.25H4.5v3.25zm6.25-3.75a1 1 0 011-1H16a1 1 0 011 1V14a1 1 0 01-1 1h-4.25a1 1 0 01-1-1V9.75zm1.5 3.75h3.25v-3.25h-3.25v3.25zM10.75 2a1 1 0 011-1H16a1 1 0 011 1v4.25a1 1 0 01-1 1h-4.25a1 1 0 01-1-1V2zm1.5 3.75h3.25V2.5h-3.25v3.25z"/></svg>`
};
export const viDeskPhone: {
  name: 'desk_phone';
  data: string;
} = {
  name: 'desk_phone',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M9.5 11c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5v-1zm.5-4a.5.5 0 00-.5.5v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1A.5.5 0 0011 7h-1zm3.5 4c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5v-1zm.5-4a.5.5 0 00-.5.5v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1A.5.5 0 0015 7h-1z"/><path fill-rule="evenodd" d="M17 1H3a2 2 0 00-2 2v10c0 1.1.9 2 2 2h14a2 2 0 002-2V3a2 2 0 00-2-2zM9 2.5v1.25c0 .97.78 1.75 1.75 1.75h3.75c.97 0 1.75-.78 1.75-1.75V2.5H17c.28 0 .5.22.5.5v10a.5.5 0 01-.5.5H7.44a2 2 0 00.06-.5V3a2 2 0 00-.06-.5H9zm1.5 0h4.25v1.25c0 .14-.11.25-.25.25h-3.75a.25.25 0 01-.25-.25V2.5zM3 2.5h2.5c.28 0 .5.22.5.5v10a.5.5 0 01-.5.5H3a.5.5 0 01-.5-.5V3c0-.28.22-.5.5-.5z"/></svg>`
};
export const viDesktop: {
  name: 'desktop';
  data: string;
} = {
  name: 'desktop',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M3 0a2 2 0 00-2 2v9c0 1.1.9 2 2 2h6.25v1.5h-2a.75.75 0 000 1.5h5.5a.75.75 0 000-1.5h-2V13H17a2 2 0 002-2V2a2 2 0 00-2-2H3zm14 1.5c.28 0 .5.22.5.5v9a.5.5 0 01-.5.5H3a.5.5 0 01-.5-.5V2c0-.28.22-.5.5-.5h14z"/></svg>`
};
export const viDevices: {
  name: 'devices';
  data: string;
} = {
  name: 'devices',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M16 2v.5h1.5V2a2 2 0 00-2-2h-12a2 2 0 00-2 2v8H.4a.4.4 0 00-.4.4c0 .88.72 1.6 1.6 1.6h8.9v-2H3V2c0-.28.22-.5.5-.5h12c.28 0 .5.22.5.5z"/><path fill-rule="evenodd" d="M19 4a1 1 0 011 1v10a1 1 0 01-1 1h-6a1 1 0 01-1-1V5a1 1 0 011-1h6zm-.5 10.5v-9h-5v9h5z"/></svg>`
};
export const viEarth: {
  name: 'earth';
  data: string;
} = {
  name: 'earth',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M7.5 4.7v.5a.3.3 0 00.59.13l.22-.45a.43.43 0 10-.81-.19z"/><path fill-rule="evenodd" d="M10 16a8 8 0 100-16 8 8 0 000 16zm5.9-5.25a.85.85 0 00-.62-.25.92.92 0 01-.51-.15l-1.02-.68a1 1 0 00-.55-.17h-.4a1 1 0 01-.55-.17l-1-.66a1 1 0 00-.55-.17h-.96a1 1 0 00-.45.1l-1.5.75a1 1 0 00-.44.45l-.24.49a1 1 0 00-.11.45v.85c0 .26.1.52.3.7l.9.92a1 1 0 00.71.29h.84c.41 0 .75.34.75.75 0 .08.01.16.04.23l-.54.02A6.5 6.5 0 015.5 3.31v.53a.4.4 0 00.74.17l.16-.32a.65.65 0 01.3-.29l.14-.07a.85.85 0 00.35-1.2 6.47 6.47 0 013.48-.6.96.96 0 00-.46.26l-1 1a.7.7 0 00-.21.5v.21c0 .28.22.5.5.5h.15c.2 0 .35-.16.35-.35 0-.1.04-.19.1-.25l.2-.2a.7.7 0 01.5-.2h.35a.35.35 0 01.25.6l-.73.73a1 1 0 01-.4.24l-.97.33a.44.44 0 00-.3.42c0 .11-.05.23-.13.3l-.58.59a1 1 0 00-.29.7v.16c0 .51.42.93.94.93.34 0 .66-.2.81-.5l.09-.18a.59.59 0 01.78-.26l.82.41a.27.27 0 00.36-.36l-.1-.2a.4.4 0 01.24-.56l.86-.28a.3.3 0 00.2-.28.3.3 0 01.3-.29h.95a.25.25 0 110 .5h-.46a.7.7 0 00-.5.2l-.19.2a.35.35 0 00.25.6h.36a.7.7 0 01.5.2l.11.12a.6.6 0 010 .86.62.62 0 00-.12.72l.4.8a.9.9 0 001.2.4l.03-.01a.8.8 0 01.36-.09c-.09.26-.18.5-.3.75z"/></svg>`
};
export const viEllipsis: {
  name: 'ellipsis';
  data: string;
} = {
  name: 'ellipsis',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M5.5 8a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm6 0a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM16 9.5a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"/></svg>`
};
export const viEnvelope: {
  name: 'envelope';
  data: string;
} = {
  name: 'envelope',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M1.5 4c0-1.1.9-2 2-2h13a2 2 0 012 2v8a2 2 0 01-2 2h-13a2 2 0 01-2-2V4zm13.94-.5H4.56l4.56 4.56c.48.48 1.28.48 1.76 0l4.56-4.56zM3 4.06V12c0 .28.22.5.5.5h13a.5.5 0 00.5-.5V4.06l-5.06 5.06a2.75 2.75 0 01-3.88 0L3 4.06z"/></svg>`
};
export const viEuro: {
  name: 'euro';
  data: string;
} = {
  name: 'euro',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12 1a7 7 0 012.14.33c.42.14.57.63.35 1.01v.02a.83.83 0 01-.97.35A5.5 5.5 0 007.1 5.5h4.27a.75.75 0 110 1.5H6.6a5.53 5.53 0 000 2h2.76a.75.75 0 010 1.5H7.1a5.5 5.5 0 006.44 2.78c.37-.1.78.02.97.35v.02c.23.38.07.87-.35 1.01a7 7 0 01-8.7-4.16H4.25a.75.75 0 010-1.5h.82a7.06 7.06 0 010-2h-.82a.75.75 0 010-1.5h1.21A7 7 0 0112 1z"/></svg>`
};
export const viFacebookMessenger: {
  name: 'facebook_messenger';
  data: string;
} = {
  name: 'facebook_messenger',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10.02.5C5.78.5 2.5 3.6 2.5 7.78c0 2.18.9 4.07 2.36 5.38.25.22.2.35.24 1.76a.6.6 0 00.85.53c1.6-.7 1.62-.76 1.89-.69 4.64 1.28 9.66-1.69 9.66-6.98C17.5 3.59 14.25.5 10.02.5zm4.5 5.6l-2.2 3.5a1.13 1.13 0 01-1.63.3L8.93 8.57a.45.45 0 00-.54 0l-2.37 1.8c-.32.24-.73-.14-.52-.48l2.2-3.5a1.13 1.13 0 011.64-.3l1.75 1.32a.45.45 0 00.55 0L14 5.62c.32-.24.73.14.52.48z"/></svg>`
};
export const viFacebook: {
  name: 'facebook';
  data: string;
} = {
  name: 'facebook',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M17.5 8a7.5 7.5 0 10-8.67 7.4v-5.23h-1.9V8h1.9V6.35c0-1.88 1.12-2.92 2.83-2.92.82 0 1.68.15 1.68.15v1.84h-.94c-.94 0-1.23.58-1.23 1.17V8h2.08l-.33 2.17h-1.75v5.24A7.5 7.5 0 0017.5 8z"/></svg>`
};
export const viFax: {
  name: 'fax';
  data: string;
} = {
  name: 'fax',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 11.5a.5.5 0 00-.5.5v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5h-1zm-.5-3c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5v-1zm4.5 3a.5.5 0 00-.5.5v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5h-1zm-.5-3c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5v-1z"/><path fill-rule="evenodd" d="M8.5 5.5V1a1 1 0 011-1h4.09a1 1 0 01.7.3l1.92 1.9a1 1 0 01.29.71V5.5h.5a2 2 0 012 2V14a2 2 0 01-2 2H3a2 2 0 01-2-2V4c0-1.1.9-2 2-2h2.5a2 2 0 012 2v1.5h1zM15 3.12L13.38 1.5H10v4h5V3.12zM7.5 7v7a2 2 0 01-.06.5H17a.5.5 0 00.5-.5V7.5A.5.5 0 0017 7H7.5zM6 4a.5.5 0 00-.5-.5H3a.5.5 0 00-.5.5v10c0 .28.22.5.5.5h2.5A.5.5 0 006 14V4z"/></svg>`
};
export const viFingerprint: {
  name: 'fingerprint';
  data: string;
} = {
  name: 'fingerprint',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M14.42 13.5c.36 0 .67-.26.73-.62a67.49 67.49 0 00.55-4.26A5.7 5.7 0 008.13 2.8a.66.66 0 00-.42.77c.1.48.64.73 1.11.6a4.2 4.2 0 015.39 4.35 46.39 46.39 0 01-.53 4.1c-.08.46.27.88.74.88zM6 5.5c.25.25.28.64.13.96a4.4 4.4 0 00-.4 1.5A56.4 56.4 0 015 12.8c-.12.56-.78.77-1.14.34a8.07 8.07 0 01-.17-.21.72.72 0 01-.14-.58 55.33 55.33 0 00.67-4.5c.06-.79.3-1.56.66-2.26.22-.4.76-.44 1.08-.12L6 5.5zm10.21 7.08c-.02.16.17.25.27.12A7.96 7.96 0 0018 8a.31.31 0 00-.46-.27l-.45.23a.7.7 0 00-.38.6v.13a48.85 48.85 0 01-.5 3.9z"/><path d="M14.83 3.54c.3.3.8.34 1.1.04a.66.66 0 00.03-.91 8.01 8.01 0 00-13.92 4.5.6.6 0 00.5.64l.5.1c.1.02.18-.05.2-.14A6.8 6.8 0 0110 1.5c1.8 0 3.56.76 4.83 2.04zm-2.89 9.19c.38.1.62.47.55.86-.1.57-.22 1.15-.34 1.7a.7.7 0 01-.54.55c-.06 0-.1.02-.16.03-.5.09-.88-.38-.78-.87.12-.54.24-1.1.34-1.67.08-.43.5-.7.93-.6z"/><path d="M12.39 10c-.45 0-.8-.4-.75-.84.03-.3.06-.58.07-.84A1.7 1.7 0 0010 6.5a1.8 1.8 0 00-1.78 1.67 42.16 42.16 0 01-.7 4.8.74.74 0 01-1.06.5.76.76 0 01-.41-.81 58.19 58.19 0 00.67-4.61A3.3 3.3 0 0110 5a3.2 3.2 0 013.21 3.43l-.08.91a.74.74 0 01-.74.66z"/><path d="M10.29 11.63c-.2 1.23-.45 2.56-.72 3.74a.7.7 0 01-.78.54 7.93 7.93 0 01-.68-.13c-.1-.03-.16-.12-.14-.21a50.77 50.77 0 001.24-7.32.8.8 0 01.79-.75.7.7 0 01.72.75c-.07.87-.22 2.1-.43 3.38z"/></svg>`
};
export const viFlagCheckered: {
  name: 'flag_checkered';
  data: string;
} = {
  name: 'flag_checkered',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M3.5 15.25v-2.66l1.48-.4a9.11 9.11 0 015.02.06c1.63.49 3.37.51 5.02.06l2.43-.66a.75.75 0 00.55-.72V.98c0-.5-.47-.85-.95-.72L15.02.8A9.12 9.12 0 0110 .75 9.12 9.12 0 004.98.69l-1.48.4V.75a.75.75 0 00-1.5 0v14.5a.75.75 0 001.5 0zm1.09-4.51l-1.09.3V9.37l1.68-.46.29-.07v1.7c-.3.05-.6.12-.88.2zm2.38-.37V8.63c.75-.04 1.51.02 2.25.19v1.7a11.3 11.3 0 00-2.25-.15zm5.75.76a7.55 7.55 0 01-2-.24V9.2c.66.13 1.33.2 2 .18v1.75zm1.5-.17v-1.7c.33-.06.67-.13 1-.22l1.28-.35v1.66l-1.88.52-.4.1zm0-3.23V5.75a8.9 8.9 0 001-.21l1.28-.35v1.94l-1.68.46-.6.14zm-1.5-1.85v2a8.45 8.45 0 01-2-.21V5.7c.66.13 1.33.2 2 .18zm0-1.5a8.45 8.45 0 01-2-.21v-1.7c.66.11 1.33.17 2 .16v1.75zm1.5-.15V2.51c.4-.06.8-.14 1.2-.25l1.08-.3v1.67l-1.68.46-.6.14zm-7.25.9c.75-.04 1.51.02 2.25.19v1.97a10 10 0 00-2.25-.17v-2zm0-1.5V1.87c.75-.04 1.51.03 2.25.21v1.7a10 10 0 00-2.25-.17zm-1.5 1.7V7.3l-.69.16-1.28.35V5.87l1.68-.46.29-.07zm0-1.53l-.69.16-1.28.35V2.65l1.88-.52.09-.02v1.7z"/></svg>`
};
export const viFlag: {
  name: 'flag';
  data: string;
} = {
  name: 'flag',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M3.5 12.6v2.65a.75.75 0 01-1.5 0V.75a.75.75 0 011.5 0v.34L4.98.7A9.12 9.12 0 0110 .75c1.63.49 3.37.51 5.02.06l2.03-.55c.48-.13.95.23.95.72v9.95c0 .34-.23.63-.55.72l-2.43.66a9.11 9.11 0 01-5.02-.06 9.11 9.11 0 00-5.02-.06l-1.48.4zm0-1.56l1.09-.3c1.91-.52 3.94-.5 5.84.07 1.37.41 2.82.43 4.2.06l1.87-.52V1.96l-1.09.3c-1.91.52-3.94.5-5.84-.07a7.62 7.62 0 00-4.2-.06l-1.87.52v8.39z"/></svg>`
};
export const viFloppyDisk: {
  name: 'floppy_disk';
  data: string;
} = {
  name: 'floppy_disk',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M3 3v10c0 1.1.9 2 2 2h10a2 2 0 002-2V5.83a2 2 0 00-.59-1.42L13.6 1.6a2 2 0 00-1.43-.6H5a2 2 0 00-2 2zm1.5 0c0-.28.22-.5.5-.5h1V5a1 1 0 001 1h4.5a1 1 0 001-1V2.62l.03.03 2.82 2.82c.1.1.15.23.15.36V13a.5.5 0 01-.5.5h-1V10a1 1 0 00-1-1H7a1 1 0 00-1 1v3.5H5a.5.5 0 01-.5-.5V3zm8 10.5h-5V11c0-.28.22-.5.5-.5h4c.28 0 .5.22.5.5v2.5zm-5-11H11V4a.5.5 0 01-.5.5H8a.5.5 0 01-.5-.5V2.5z"/></svg>`
};
export const viFolder: {
  name: 'folder';
  data: string;
} = {
  name: 'folder',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M16.5 12.5a.5.5 0 01-.5.5H4a.5.5 0 01-.5-.5v-9c0-.28.22-.5.5-.5h2.76c.2 0 .37.1.45.28l.31.61A2 2 0 009.31 5H16c.28 0 .5.22.5.5v7zM4 1.5a2 2 0 00-2 2v9c0 1.1.9 2 2 2h12a2 2 0 002-2v-7a2 2 0 00-2-2H9.3a.5.5 0 01-.44-.28l-.3-.61a2 2 0 00-1.8-1.11H4z"/></svg>`
};
export const viGauge: {
  name: 'gauge';
  data: string;
} = {
  name: 'gauge',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M14 6.44c.3.27.34.74.06 1.05l-1.92 2.2A2.5 2.5 0 0011 8.72l1.93-2.2a.75.75 0 011.05-.07z"/><path fill-rule="evenodd" d="M17.5 14.34c-.38.16-.72.16-1.42.16H3.92c-.7 0-1.04 0-1.42-.16a2.4 2.4 0 01-.83-.65c-.24-.32-.3-.56-.41-1.05A9.02 9.02 0 0110 1.5a9 9 0 018.74 11.14c-.11.49-.17.73-.41 1.05a2.4 2.4 0 01-.83.65zm-.21-2.05A7.52 7.52 0 0010 3a7.5 7.5 0 00-7.11 9.8 1.13 1.13 0 00.2.16 8.9 8.9 0 00.82.04H8.5a2.5 2.5 0 113 0h4.58a8.9 8.9 0 00.84-.05 1.15 1.15 0 00.2-.16.4.4 0 00.04-.05l.01-.03.04-.14.08-.28zM10 12a1 1 0 100-2 1 1 0 000 2z"/></svg>`
};
export const viGear: {
  name: 'gear';
  data: string;
} = {
  name: 'gear',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M13 8a3 3 0 11-6 0 3 3 0 016 0zm-1.5 0a1.5 1.5 0 10-3 0 1.5 1.5 0 003 0z"/><path fill-rule="evenodd" d="M5.3 2.4l.75.43A6.5 6.5 0 017.5 2v-.88c0-.43.28-.82.7-.92a8.02 8.02 0 013.6 0c.42.1.7.49.7.92V2c.51.21 1 .5 1.45.83l.75-.43a.93.93 0 011.15.14c.38.41.72.86 1 1.34l.16.25c.26.49.48 1 .64 1.53a.92.92 0 01-.44 1.07l-.76.43c.07.57.07 1.13 0 1.68l.76.43c.37.22.57.65.44 1.07a7.95 7.95 0 01-.64 1.53l-.15.25c-.3.48-.63.93-1.01 1.34a.93.93 0 01-1.15.14l-.75-.43a6.5 6.5 0 01-1.45.83v.88c0 .43-.28.82-.7.92a8.02 8.02 0 01-3.6 0 .92.92 0 01-.7-.92V14c-.51-.21-1-.5-1.45-.83l-.75.43a.93.93 0 01-1.15-.14 7.66 7.66 0 01-1-1.34L3 11.87c-.27-.48-.49-1-.65-1.53a.92.92 0 01.44-1.07l.76-.43a6.46 6.46 0 010-1.68l-.76-.43a.92.92 0 01-.44-1.07c.16-.53.38-1.05.65-1.53l.14-.25c.3-.48.63-.93 1.01-1.34A.93.93 0 015.3 2.4zM9 2v.67a.5.5 0 01-.3.46l-.62.25a5 5 0 00-1.12.65l-.53.4a.5.5 0 01-.55.04l-.57-.33a.47.47 0 00-.63.12l-.25.38-.13.23-.2.39c-.1.22 0 .48.2.6l.58.34c.18.1.27.3.25.5l-.09.66c-.05.42-.06.85 0 1.28l.09.66a.5.5 0 01-.25.5l-.57.33a.47.47 0 00-.2.61c.06.13.12.26.2.39l.12.23.25.38c.14.2.41.25.63.12l.57-.33a.5.5 0 01.55.04l.53.4c.35.26.72.48 1.12.65l.61.25a.5.5 0 01.31.46V14c0 .25.18.46.43.49a6.6 6.6 0 001.14 0A.47.47 0 0011 14v-.66c0-.2.12-.38.3-.46l.62-.25c.41-.17.78-.4 1.12-.65l.53-.4a.5.5 0 01.55-.04l.57.33c.22.13.49.08.63-.12l.25-.38.13-.23.2-.39a.47.47 0 00-.2-.6l-.58-.34a.5.5 0 01-.25-.5l.09-.66c.05-.42.06-.85 0-1.28l-.09-.66a.5.5 0 01.25-.5l.57-.33c.22-.13.31-.39.2-.61a6.45 6.45 0 00-.2-.39l-.12-.23a6.53 6.53 0 00-.25-.38.47.47 0 00-.63-.12l-.57.33a.5.5 0 01-.55-.04l-.53-.4a5.02 5.02 0 00-1.12-.65l-.61-.25a.5.5 0 01-.31-.46V2a.47.47 0 00-.43-.49 6.61 6.61 0 00-1.15 0A.47.47 0 009 2z"/></svg>`
};
export const viGooglePlay: {
  name: 'google_play';
  data: string;
} = {
  name: 'google_play',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.08 7.37L5.61.88l8.23 4.72-1.76 1.77zM3.93.5c-.38.2-.64.56-.64 1.03v12.94c0 .47.26.83.64 1.03L11.45 8 3.93.5zm12.46 6.61l-1.73-1-1.93 1.9 1.93 1.88 1.76-1c.53-.42.53-1.36-.03-1.78zM5.6 15.12l8.23-4.72-1.76-1.76-6.47 6.48z"/></svg>`
};
export const viHeadset: {
  name: 'headset';
  data: string;
} = {
  name: 'headset',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M16.5 13c0 .83-.67 1.5-1.5 1.5h-3c0-.83-.67-1.5-1.5-1.5h-1c-.83 0-1.5.67-1.5 1.5v.75c0 .41.34.75.75.75H15a3 3 0 003-3V8A8 8 0 102 8v.25a.75.75 0 001.5 0V8a6.5 6.5 0 0113 0v5z"/><path fill-rule="evenodd" d="M9 6.5a1 1 0 00-1-1H6.5a2 2 0 00-2 2v2c0 1.1.9 2 2 2H8a1 1 0 001-1v-4zM7.5 10h-1a.5.5 0 01-.5-.5v-2c0-.28.22-.5.5-.5h1v3zM11 6.5a1 1 0 011-1h1.5a2 2 0 012 2v2a2 2 0 01-2 2H12a1 1 0 01-1-1v-4zm1.5 3.5h1a.5.5 0 00.5-.5v-2a.5.5 0 00-.5-.5h-1v3z"/></svg>`
};
export const viHeartBroken: {
  name: 'heart_broken';
  data: string;
} = {
  name: 'heart_broken',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 3.3L8.88 2.18A4.03 4.03 0 002 5.03v.37c0 1.22.48 2.38 1.34 3.24L9.3 14.6a1 1 0 001.42 0l5.95-5.95A4.58 4.58 0 0018 5.4v-.37a4.03 4.03 0 00-6.88-2.85L10 3.3zm0 2.12l2.18-2.18a2.53 2.53 0 014.32 1.79v.37c0 .82-.32 1.6-.9 2.18l-5.6 5.6-5.6-5.6a3.08 3.08 0 01-.9-2.18v-.37a2.53 2.53 0 014.32-1.8l.52.53L7 6l3 1.5-1 2 4-2L10 6v-.58z"/></svg>`
};
export const viHeartHalf: {
  name: 'heart_half';
  data: string;
} = {
  name: 'heart_half',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 3.3L8.88 2.18A4.03 4.03 0 002 5.03v.37c0 1.22.48 2.38 1.34 3.24L9.3 14.6a1 1 0 001.42 0l5.95-5.95A4.58 4.58 0 0018 5.4v-.37a4.03 4.03 0 00-6.88-2.85L10 3.3zm0 2.12v7.76l-5.6-5.6a3.08 3.08 0 01-.9-2.18v-.37a2.53 2.53 0 014.32-1.8L10 5.44z"/></svg>`
};
export const viHeart: {
  name: 'heart';
  data: string;
} = {
  name: 'heart',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 5.42L7.82 3.24A2.53 2.53 0 003.5 5.03v.37c0 .82.32 1.6.9 2.18l5.6 5.6 5.6-5.6c.58-.58.9-1.36.9-2.18v-.37a2.53 2.53 0 00-4.32-1.8L10 5.44zm0-2.12l1.12-1.12A4.03 4.03 0 0118 5.03v.37c0 1.22-.48 2.38-1.34 3.24L10.7 14.6a1 1 0 01-1.42 0L3.34 8.64A4.58 4.58 0 012 5.4v-.37a4.03 4.03 0 016.88-2.85L10 3.3z"/></svg>`
};
export const viHistory: {
  name: 'history';
  data: string;
} = {
  name: 'history',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M6.32 12.74a.84.84 0 00-1.1.03.7.7 0 00.03 1.04A7.5 7.5 0 104 3.5V1.74a.75.75 0 00-1.5 0V6a1 1 0 001 1h3.25a.75.75 0 000-1.5h-2.2a6 6 0 111.77 7.24z"/><path d="M9.25 8V3.75a.75.75 0 011.5 0v3.94l1.43 1.43a.75.75 0 11-1.06 1.06L9.53 8.6a.76.76 0 01-.03-.03.75.75 0 01-.25-.56z"/></svg>`
};
export const viHome: {
  name: 'home';
  data: string;
} = {
  name: 'home',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4.5 7.83V14c0 .28.22.5.5.5h10a.5.5 0 00.5-.5V7.83a.5.5 0 00-.15-.36l-5-5a.5.5 0 00-.7 0l-5 5a.5.5 0 00-.15.36zM3 14V7.83a2 2 0 01.59-1.42l5-5a2 2 0 012.82 0l5 5A2 2 0 0117 7.83V14a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg>`
};
export const viIdCard: {
  name: 'id_card';
  data: string;
} = {
  name: 'id_card',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M7.5 9.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5zm0-1.5a1 1 0 110-2 1 1 0 010 2z"/><path d="M15.25 5h-3a.75.75 0 000 1.5h3a.75.75 0 000-1.5zm-3 3h3a.75.75 0 010 1.5h-3a.75.75 0 010-1.5z"/><path fill-rule="evenodd" d="M17 15a2 2 0 002-2V3a2 2 0 00-2-2H3a2 2 0 00-2 2v10c0 1.1.9 2 2 2h14zm.5-11.5V13a.5.5 0 01-.5.5h-5.09c.16-.58.11-1.22-.22-1.7a2.41 2.41 0 00-1.56-1.07 15.3 15.3 0 00-5.26 0c-.63.1-1.18.5-1.56 1.06a2.08 2.08 0 00-.22 1.71H3a.5.5 0 01-.5-.5V3.5h15zM4.71 13.48a1.1 1.1 0 01-.2-.53c-.03-.2.02-.29.04-.31.2-.29.41-.4.57-.43a13.8 13.8 0 014.76 0c.16.02.38.14.57.43.02.02.07.12.04.31-.02.2-.1.4-.2.53l-.02.02H4.73l-.02-.02z"/></svg>`
};
export const viImage: {
  name: 'image';
  data: string;
} = {
  name: 'image',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.5 7a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"/><path fill-rule="evenodd" d="M5 1a2 2 0 00-2 2v10c0 1.1.9 2 2 2h10a2 2 0 002-2V3a2 2 0 00-2-2H5zm10 12.5h-.44l-5.2-5.2a2.75 2.75 0 00-3.77-.1l-1.09.96V3c0-.28.22-.5.5-.5h10c.28 0 .5.22.5.5v10a.5.5 0 01-.5.5zM6.59 9.31c.5-.44 1.25-.41 1.71.05l4.14 4.14H5a.5.5 0 01-.5-.5v-1.83l2.09-1.86z"/></svg>`
};
export const viLaptop: {
  name: 'laptop';
  data: string;
} = {
  name: 'laptop',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M2 12V4c0-1.1.9-2 2-2h12a2 2 0 012 2v8h1.1c.22 0 .4.18.4.4 0 .88-.72 1.6-1.6 1.6H2.1a1.6 1.6 0 01-1.6-1.6c0-.22.18-.4.4-.4H2zm14.5-8a.5.5 0 00-.5-.5H4a.5.5 0 00-.5.5v8h13V4z"/></svg>`
};
export const viLayersPlus: {
  name: 'layers_plus';
  data: string;
} = {
  name: 'layers_plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M8.88 1.93a.25.25 0 01.24 0l4.57 2.61c.8.16 1.45.74 1.7 1.5.6-.79.42-2.01-.54-2.56L9.87.63a1.8 1.8 0 00-1.74 0L3.15 3.48a1.75 1.75 0 000 3.04l4.55 2.6c.4-.38.95-.62 1.55-.62H11V7L9.12 8.06a.25.25 0 01-.24 0L3.89 5.22a.25.25 0 010-.44l4.99-2.85zM3.9 9.22L7 11c.13 1.13 1.08 2 2.24 2h1.26l-.64.37c-.54.3-1.2.3-1.74 0l-4.98-2.85a1.75 1.75 0 01-.53-2.58l1.37.79-.1.05a.25.25 0 000 .44zm11.6-.72h.16a1.8 1.8 0 00-.16-.38v.38z"/><path d="M14 6.75V10h3.25a.75.75 0 010 1.5H14v3.25a.75.75 0 01-1.5 0V11.5H9.25a.75.75 0 010-1.5h3.25V6.75a.75.75 0 011.5 0z"/></svg>`
};
export const viLayers: {
  name: 'layers';
  data: string;
} = {
  name: 'layers',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10.87 1.63a1.8 1.8 0 00-1.74 0L4.15 4.48a1.75 1.75 0 000 3.04l4.98 2.85c.54.3 1.2.3 1.74 0l4.98-2.85a1.75 1.75 0 000-3.04l-4.98-2.85zm-1 1.3a.25.25 0 01.25 0l4.99 2.85c.17.1.17.34 0 .44l-4.99 2.85a.25.25 0 01-.24 0L4.89 6.22a.25.25 0 010-.44l4.99-2.85z"/><path d="M4.15 11.52a1.75 1.75 0 01-.53-2.58l1.37.79-.1.05a.25.25 0 000 .44l4.99 2.85c.07.04.17.04.24 0l4.99-2.85a.25.25 0 000-.44l-.1-.05 1.37-.79c.6.8.43 2.03-.53 2.58l-4.98 2.85c-.54.3-1.2.3-1.74 0l-4.98-2.85z"/></svg>`
};
export const viLightbulbOn: {
  name: 'lightbulb_on';
  data: string;
} = {
  name: 'lightbulb_on',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.2 9.48c.71.68 1.3 1.54 1.3 2.52h5c0-.98.59-1.84 1.3-2.52A5.48 5.48 0 0010 0a5.5 5.5 0 00-3.8 9.48zM14 5.5a4 4 0 01-1.24 2.9 6 6 0 00-1.47 2.1H8.7a6 6 0 00-1.47-2.1A4 4 0 1114 5.5z"/><path d="M8.28 15.12c-.5-.39-.78-.99-.78-1.62h5c0 .63-.29 1.23-.78 1.62l-.26.22c-.14.1-.25.24-.33.4a.48.48 0 01-.43.26H9.3a.48.48 0 01-.43-.26 1.2 1.2 0 00-.33-.4l-.26-.22zM3.5 6c0 .41-.34.75-.75.75h-2a.75.75 0 010-1.5h2c.41 0 .75.34.75.75zm15.75.75a.75.75 0 000-1.5h-2a.75.75 0 000 1.5h2zm-14.88-4a.75.75 0 01-1.02.27l-1.74-1a.75.75 0 11.75-1.3l1.74 1c.36.21.48.67.27 1.03zm13.27 8.52a.75.75 0 00.75-1.3l-1.74-1a.75.75 0 00-.75 1.3l1.74 1zM4.37 9.25c.2.36.09.82-.27 1.02l-1.74 1a.75.75 0 01-.75-1.3l1.74-1a.75.75 0 011.02.28zm14.02-7.23a.75.75 0 00-.75-1.3l-1.74 1a.75.75 0 10.75 1.3l1.74-1z"/></svg>`
};
export const viLightbulb: {
  name: 'lightbulb';
  data: string;
} = {
  name: 'lightbulb',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.2 9.48c.71.68 1.3 1.54 1.3 2.52h5c0-.98.59-1.84 1.3-2.52A5.48 5.48 0 0010 0a5.5 5.5 0 00-3.8 9.48zM14 5.5a4 4 0 01-1.24 2.9 6 6 0 00-1.47 2.1H8.7a6 6 0 00-1.47-2.1A4 4 0 1114 5.5z"/><path d="M8.28 15.12c-.5-.39-.78-.99-.78-1.62h5c0 .63-.29 1.23-.78 1.62l-.26.22c-.14.1-.25.24-.33.4a.48.48 0 01-.43.26H9.3a.48.48 0 01-.43-.26 1.2 1.2 0 00-.33-.4l-.26-.22z"/></svg>`
};
export const viLinkedin: {
  name: 'linkedin';
  data: string;
} = {
  name: 'linkedin',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M16 1H4a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V2a1 1 0 00-1-1zM7.23 13H5.16V6.32h2.07V13zM6.2 5.4a1.2 1.2 0 110-2.4 1.2 1.2 0 010 2.4zm8.82 7.6h-2.08V9.75c0-.78-.01-1.77-1.07-1.77-1.08 0-1.25.84-1.25 1.71V13H8.53V6.32h2v.91h.02a2.2 2.2 0 011.97-1.08c2.1 0 2.49 1.39 2.49 3.19V13z"/></svg>`
};
export const viListOl: {
  name: 'list_ol';
  data: string;
} = {
  name: 'list_ol',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M4.82 5h-.86V2.02c-.1.06-.2.12-.33.17-.12.04-.25.1-.4.14L3 1.63A4.38 4.38 0 004.3 1h.52v4zM3.08 9.7v.3H5.7v-.72H4.08c0-.05.01-.1.04-.16a.7.7 0 01.14-.18l.2-.17a13.4 13.4 0 00.62-.47c.12-.1.22-.2.32-.32a1.32 1.32 0 00.3-.87 1 1 0 00-.34-.8c-.23-.2-.53-.31-.92-.31A1.5 1.5 0 003 6.93l.7.29a1 1 0 01.27-.38c.1-.1.22-.14.36-.14.16 0 .28.04.37.12.09.08.13.2.13.34a.74.74 0 01-.19.5 4.48 4.48 0 01-.52.46l-.35.27a2.13 2.13 0 00-.59.77c-.07.16-.1.34-.1.54zm.57 4.22L3 14.3c.13.23.3.4.53.52.22.12.5.18.84.18.42 0 .76-.1 1.01-.32.26-.2.39-.5.39-.85a.88.88 0 00-.21-.6.98.98 0 00-.59-.3v-.02c.23-.07.4-.19.51-.35a.92.92 0 00.17-.55c0-.32-.1-.56-.32-.74a1.4 1.4 0 00-.91-.27c-.32 0-.6.07-.82.21-.23.14-.4.32-.51.53l.63.3a.72.72 0 01.26-.29c.1-.06.22-.1.34-.1a.5.5 0 01.33.12.4.4 0 01.14.32c0 .18-.07.32-.2.4-.12.09-.3.13-.56.13h-.29v.66h.32c.26 0 .47.05.62.14.15.1.22.22.22.4 0 .16-.05.29-.17.38a.66.66 0 01-.41.13.69.69 0 01-.41-.12.74.74 0 01-.26-.3zM7.75 2.5a.75.75 0 000 1.5h8.5a.75.75 0 000-1.5h-8.5zM7 8.25c0-.41.34-.75.75-.75h8.5a.75.75 0 010 1.5h-8.5A.75.75 0 017 8.25zm.75 4.25a.75.75 0 000 1.5h8.5a.75.75 0 000-1.5h-8.5z"/></svg>`
};
export const viLock: {
  name: 'lock';
  data: string;
} = {
  name: 'lock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10.75 10.25a1.25 1.25 0 10-1.5 0v2a.75.75 0 001.5 0v-2z"/><path fill-rule="evenodd" d="M13 5h2a2 2 0 012 2v7a2 2 0 01-2 2H5a2 2 0 01-2-2V7c0-1.1.9-2 2-2h2V3a3 3 0 016 0v2zm-1.5 0V3a1.5 1.5 0 00-3 0v2h3zm-7 2v7c0 .28.22.5.5.5h10a.5.5 0 00.5-.5V7a.5.5 0 00-.5-.5H5a.5.5 0 00-.5.5z"/></svg>`
};
export const viMapMarkerSlashed: {
  name: 'map_marker_slashed';
  data: string;
} = {
  name: 'map_marker_slashed',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M9.55 13.54l-.68-1.23-1.1 1.1.96 1.74a.9.9 0 001.53.06l4.3-6.62c.57-.87.86-1.86.88-2.84L13.1 8.08l-3.56 5.46zM7.22 2.85a3.94 3.94 0 015.13-.38l1.07-1.07a5.44 5.44 0 00-7.26.38l-.12.12a5.6 5.6 0 00-.94 6.65l.41.76 1.1-1.1-.2-.38a4.1 4.1 0 01.7-4.87l.1-.11zm8.78.21A.75.75 0 1014.94 2L4 12.94A.75.75 0 005.06 14L16 3.06z"/></svg>`
};
export const viMapMarker: {
  name: 'map_marker';
  data: string;
} = {
  name: 'map_marker',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M12.78 2.85a3.94 3.94 0 00-5.56 0l-.12.1a4.1 4.1 0 00-.69 4.88l3.14 5.71 3.75-5.76a3.94 3.94 0 00-.52-4.93zM6.15 1.78a5.44 5.44 0 018.4 6.81l-4.29 6.62a.9.9 0 01-1.53-.06L5.1 8.55a5.6 5.6 0 01.94-6.65l.11-.12z"/></svg>`
};
export const viMessage: {
  name: 'message';
  data: string;
} = {
  name: 'message',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M5.75 4.5h3.5a.75.75 0 100-1.5h-3.5a.75.75 0 000 1.5zm6 0h1.5a.75.75 0 000-1.5h-1.5a.75.75 0 000 1.5zm.5 3h-6.5a.75.75 0 010-1.5h6.5a.75.75 0 010 1.5z"/><path fill-rule="evenodd" d="M9.73 12.22L5.4 15.68a.25.25 0 01-.41-.2V12H4a2 2 0 01-2-2V2c0-1.1.9-2 2-2h12a2 2 0 012 2v8a2 2 0 01-2 2h-5.65a1 1 0 00-.62.22zM6.5 10.5v2.38l2.29-1.83c.44-.36 1-.55 1.56-.55H16a.5.5 0 00.5-.5V2a.5.5 0 00-.5-.5H4a.5.5 0 00-.5.5v8c0 .28.22.5.5.5h2.5z"/></svg>`
};
export const viNetwork: {
  name: 'network';
  data: string;
} = {
  name: 'network',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M4.34 7.19c.34-.37.57-.84.64-1.36l2.24 1.04c-.3.4-.52.86-.64 1.36L4.34 7.2zm11.68-1.67a2.5 2.5 0 01-.89-1.21l-2.82 2.06c.38.34.68.75.9 1.21l2.81-2.06zm-3.73 6.13c.38-.33.68-.74.9-1.2l2.22 1.67c-.48.2-.83.66-.9 1.2l-2.22-1.67z"/><path fill-rule="evenodd" d="M10 11a2 2 0 110-4 2 2 0 010 4zm0 1.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7zm7.5-8a1 1 0 110-2 1 1 0 010 2zm0 1.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5zm-15 .5a1 1 0 110-2 1 1 0 010 2zm0 1.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5z"/><path d="M17.5 13.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm-7-11a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z"/></svg>`
};
export const viParachute: {
  name: 'parachute';
  data: string;
} = {
  name: 'parachute',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M13 12a2 2 0 00-.18-.84L16.69 6c.64-.05 1.11-.7.91-1.33C16.96 2.61 15.66 0 10 0S3.04 2.61 2.4 4.67c-.2.63.27 1.28.91 1.33l3.87 5.16A2 2 0 007 12v2c0 1.1.9 2 2 2h2a2 2 0 002-2v-2zm2.96-7.5h-2.79a7.57 7.57 0 00-.77-2.79 5.3 5.3 0 012.33 1.01c.6.5.96 1.1 1.23 1.78zM10.75 6h4.06l-3.1 4.13A2 2 0 0011 10h-.25V6zm-1.5 4H9a2 2 0 00-.71.13L5.19 6h4.06v4zM10 1.5c.18 0 .59.12.99.77.28.46.54 1.17.67 2.23H8.34a5.6 5.6 0 01.67-2.23c.4-.65.81-.77.99-.77zm-3.17 3H4.04c.27-.68.63-1.29 1.23-1.78.48-.4 1.2-.78 2.33-1-.37.69-.65 1.6-.77 2.78zm2.17 7h2c.28 0 .5.22.5.5v2a.5.5 0 01-.5.5H9a.5.5 0 01-.5-.5v-2c0-.28.22-.5.5-.5z"/></svg>`
};
export const viPen: {
  name: 'pen';
  data: string;
} = {
  name: 'pen',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M7.43 14.57l9.66-9.66a2 2 0 000-2.82L15.9.9a2 2 0 00-2.82 0l-9.66 9.66a2 2 0 00-.55 1.02l-.73 3.67a.5.5 0 00.59.6l3.67-.74a2 2 0 001.02-.55zm5.63-11.5l1.88 1.87-8.57 8.57a.5.5 0 01-.26.14l-2.2.44.44-2.2a.5.5 0 01.14-.26l8.57-8.57z"/></svg>`
};
export const viPhoneGear: {
  name: 'phone_gear';
  data: string;
} = {
  name: 'phone_gear',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 17"><path d="M5.91 8.18l-.09-.19a2 2 0 01.38-2.3l.6-.62-.66-2.22a.5.5 0 00-.62-.34l-1.72.51c-.23.08-.3.25-.3.34.1 2.1.63 4.48 2.08 6.39a8.4 8.4 0 002.89 2.4c.08.12.18.22.29.31v.08a2 2 0 00-.66 1.1C3.4 11.43 2.17 6.89 2 3.45c-.03-.86.55-1.6 1.37-1.85l1.72-.52a2 2 0 012.49 1.35l.75 2.5a1 1 0 01-.25 1l-.82.83a.5.5 0 00-.1.57l.1.19-1.35.67z"/><path d="M7.26 7.5A5 5 0 008.7 9.27l-.1.15v.01l-.1.17c-.12.21-.22.42-.3.64-.07.14-.1.28-.13.42A6.5 6.5 0 015.9 8.19l1.35-.67z"/><path fill-rule="evenodd" d="M9.59 14.2c.07.17.14.32.23.48l.08.14c.09.15.19.3.3.44.14.18.4.22.6.1l.23-.13a.55.55 0 01.6.05c.24.18.5.33.78.45.2.09.35.28.35.5v.26c0 .23.16.44.39.47a4.54 4.54 0 001.21 0c.23-.03.4-.24.4-.47v-.26c0-.22.14-.41.35-.5.27-.12.53-.27.77-.45a.55.55 0 01.6-.05l.23.13c.2.12.46.08.6-.1.11-.14.21-.29.3-.44l.09-.14c.08-.16.16-.31.22-.48a.46.46 0 00-.2-.57l-.24-.13a.55.55 0 01-.25-.55 3.54 3.54 0 000-.9.55.55 0 01.25-.55l.23-.13c.2-.12.3-.36.21-.57a4.48 4.48 0 00-.22-.48l-.09-.14c-.09-.15-.19-.3-.3-.44a.47.47 0 00-.6-.1l-.23.13a.55.55 0 01-.6-.05 3.5 3.5 0 00-.77-.45.55.55 0 01-.35-.5v-.26a.46.46 0 00-.4-.47 4.54 4.54 0 00-1.21 0 .46.46 0 00-.4.47v.26c0 .22-.14.41-.34.5a3.5 3.5 0 00-.77.45.55.55 0 01-.61.05l-.23-.13a.46.46 0 00-.6.1c-.11.14-.21.29-.3.44l-.08.14c-.09.16-.16.31-.23.48-.09.21 0 .45.21.57l.23.13c.19.11.28.34.25.55a3.54 3.54 0 000 .9.55.55 0 01-.25.55l-.23.13c-.2.12-.3.36-.21.57zm2.17-1.7a2 2 0 114 0 2 2 0 01-4 0z"/></svg>`
};
export const viPhone: {
  name: 'phone';
  data: string;
} = {
  name: 'phone',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.91 8.18a6.5 6.5 0 002.91 2.9l.19.1a2 2 0 002.3-.37l.62-.62 2.22.67a.5.5 0 01.34.62l-.5 1.66c-.07.23-.26.32-.38.31-4.24-.28-6.63-1.85-8.04-3.7a11.44 11.44 0 01-2.06-6.39c0-.1.06-.26.3-.34l1.7-.5a.5.5 0 01.63.33l.67 2.22-.62.61A2 2 0 006.82 8l.1.19zm1.34-.67l-.09-.19a.5.5 0 01.1-.57l.82-.83a1 1 0 00.25-1l-.76-2.5a2 2 0 00-2.49-1.35l-1.7.52c-.83.24-1.41.99-1.37 1.84.2 4.52 2.28 10.9 11.5 11.52a1.9 1.9 0 001.92-1.38l.5-1.65a2 2 0 00-1.35-2.5l-2.5-.75a1 1 0 00-1 .25l-.83.83a.5.5 0 01-.57.09l-.19-.1a5 5 0 01-2.24-2.23z"/></svg>`
};
export const viPlus: {
  name: 'plus';
  data: string;
} = {
  name: 'plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.25 8.75v5.5a.75.75 0 001.5 0v-5.5h5.5a.75.75 0 000-1.5h-5.5v-5.5a.75.75 0 00-1.5 0v5.5h-5.5a.75.75 0 000 1.5h5.5z"/></svg>`
};
export const viPresent: {
  name: 'present';
  data: string;
} = {
  name: 'present',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 4L8.68 1.37A2.47 2.47 0 004 2.47v.28c0 .45.1.87.3 1.25H4a2 2 0 00-2 2v2a1 1 0 001 1h.5v5c0 1.1.9 2 2 2h9a2 2 0 002-2V9h.5a1 1 0 001-1V6a2 2 0 00-2-2h-.3c.2-.38.3-.8.3-1.25v-.28a2.47 2.47 0 00-4.68-1.1L10 4zM5.5 2.75v-.28a.97.97 0 011.84-.43L8.32 4H6.75C6.06 4 5.5 3.44 5.5 2.75zM11.68 4l.98-1.96a.97.97 0 011.84.43v.28c0 .69-.56 1.25-1.25 1.25h-1.57zM4 5.5h12c.28 0 .5.22.5.5v1.5h-13V6c0-.28.22-.5.5-.5zM10.75 9H15v5a.5.5 0 01-.5.5h-3.75V9zm-1.5 5.5H5.5A.5.5 0 015 14V9h4.25v5.5z"/></svg>`
};
export const viRefresh: {
  name: 'refresh';
  data: string;
} = {
  name: 'refresh',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M15.33 5.25a6 6 0 10-1.65 7.49.84.84 0 011.1.03.7.7 0 01-.03 1.04 7.5 7.5 0 111.75-9.55V1A.75.75 0 0118 1v4.75a1 1 0 01-1 1h-4.75a.75.75 0 010-1.5h3.08z"/></svg>`
};
export const viSearch: {
  name: 'search';
  data: string;
} = {
  name: 'search',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M17 6a5 5 0 01-7.97 4.03L4.06 15A.75.75 0 113 13.94l4.97-4.97A5 5 0 1117 6zm-1.5 0a3.5 3.5 0 10-7 0 3.5 3.5 0 007 0z"/></svg>`
};
export const viSend: {
  name: 'send';
  data: string;
} = {
  name: 'send',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M2.48 14.74l16.3-6.27a.5.5 0 000-.94L2.49 1.26a1 1 0 00-1.31 1.25L2.9 7.68a1 1 0 010 .64l-1.72 5.17a1 1 0 001.3 1.25zM15.82 8l-12.9 4.96 1.4-4.17.01-.04h5.92a.75.75 0 000-1.5H4.33l-.01-.04-1.4-4.17L15.83 8z"/></svg>`
};
export const viServer: {
  name: 'server';
  data: string;
} = {
  name: 'server',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M14 4.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM10.75 5a.75.75 0 100-1.5.75.75 0 000 1.5zm2.5 5a.75.75 0 100-1.5.75.75 0 000 1.5zm-1.75-.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"/><path fill-rule="evenodd" d="M3 3c0-1.1.9-2 2-2h10a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V3zm2-.5a.5.5 0 00-.5.5v3h11V3a.5.5 0 00-.5-.5H5zm-.5 5V13c0 .28.22.5.5.5h10a.5.5 0 00.5-.5V7.5h-11z"/></svg>`
};
export const viShieldDanger: {
  name: 'shield_danger';
  data: string;
} = {
  name: 'shield_danger',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M7.35 9.6L8.94 8l-1.6-1.6a.75.75 0 111.07-1.05L10 6.94l1.6-1.6a.75.75 0 011.05 1.07L11.06 8l1.6 1.6a.75.75 0 01-1.07 1.05L10 9.06l-1.6 1.6a.75.75 0 01-1.05-1.07z"/><path fill-rule="evenodd" d="M9.3.26a2 2 0 011.4 0l5.89 2.21a1.87 1.87 0 011.23 2.02C17.1 8.97 14.64 16 10 16 5.36 16 2.9 8.97 2.18 4.5c-.14-.89.4-1.72 1.23-2.03L9.3.27zM3.94 3.88c-.24.08-.3.27-.28.38.34 2.12 1.1 4.82 2.27 6.94 1.21 2.18 2.6 3.3 4.07 3.3 1.47 0 2.86-1.12 4.07-3.3a22.44 22.44 0 002.27-6.94c.01-.11-.04-.3-.28-.38l-5.88-2.21a.5.5 0 00-.36 0l-5.88 2.2z"/></svg>`
};
export const viShieldKeyhole: {
  name: 'shield_keyhole';
  data: string;
} = {
  name: 'shield_keyhole',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11.5 7c0 .56-.3 1.04-.75 1.3v1.45a.75.75 0 01-1.5 0V8.3A1.5 1.5 0 1111.5 7z"/><path fill-rule="evenodd" d="M9.3.26a2 2 0 011.4 0l5.89 2.21a1.87 1.87 0 011.23 2.02C17.1 8.97 14.64 16 10 16 5.36 16 2.9 8.97 2.18 4.5c-.14-.89.4-1.72 1.23-2.03L9.3.27zM3.94 3.88c-.24.08-.3.27-.28.38.34 2.12 1.1 4.82 2.27 6.94 1.21 2.18 2.6 3.3 4.07 3.3 1.47 0 2.86-1.12 4.07-3.3a22.44 22.44 0 002.27-6.94c.01-.11-.04-.3-.28-.38l-5.88-2.21a.5.5 0 00-.36 0l-5.88 2.2z"/></svg>`
};
export const viShieldPlus: {
  name: 'shield_plus';
  data: string;
} = {
  name: 'shield_plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M7 7.25h2.25V5a.75.75 0 011.5 0v2.25H13a.75.75 0 010 1.5h-2.25V11a.75.75 0 01-1.5 0V8.75H7a.75.75 0 010-1.5z"/><path fill-rule="evenodd" d="M9.3.26a2 2 0 011.4 0l5.89 2.21a1.87 1.87 0 011.23 2.02C17.1 8.97 14.64 16 10 16 5.36 16 2.9 8.97 2.18 4.5c-.14-.89.4-1.72 1.23-2.03L9.3.27zM3.94 3.88c-.24.08-.3.27-.28.38.34 2.12 1.1 4.82 2.27 6.94 1.21 2.18 2.6 3.3 4.07 3.3 1.47 0 2.86-1.12 4.07-3.3a22.44 22.44 0 002.27-6.94c.01-.11-.04-.3-.28-.38l-5.88-2.21a.5.5 0 00-.36 0l-5.88 2.2z"/></svg>`
};
export const viShield: {
  name: 'shield';
  data: string;
} = {
  name: 'shield',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.82 1.67l-5.88 2.2c-.24.1-.3.28-.28.39.34 2.12 1.1 4.82 2.27 6.94 1.21 2.18 2.6 3.3 4.07 3.3 1.47 0 2.86-1.12 4.07-3.3a22.44 22.44 0 002.27-6.94c.01-.11-.04-.3-.28-.38l-5.88-2.21a.5.5 0 00-.36 0zm-6.4.8L9.3.27a2 2 0 011.4 0l5.89 2.2a1.87 1.87 0 011.23 2.02C17.1 8.97 14.64 16 10 16 5.36 16 2.9 8.97 2.18 4.5c-.14-.89.4-1.72 1.23-2.03z"/></svg>`
};
export const viSimCard: {
  name: 'sim_card';
  data: string;
} = {
  name: 'sim_card',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 10h3V9a1 1 0 00-1-1h-2v2zm-3 2v-1h3v2H8a1 1 0 01-1-1zm6 0v-1h-2v2h1a1 1 0 001-1zM7 9v1h2V8H8a1 1 0 00-1 1z"/><path fill-rule="evenodd" d="M4 2v12c0 1.1.9 2 2 2h8a2 2 0 002-2V4.83a2 2 0 00-.59-1.42L12.6.6a2 2 0 00-1.43-.6H6a2 2 0 00-2 2zm1.5 12V2c0-.28.22-.5.5-.5h5.17a.5.5 0 01.36.15l2.82 2.82c.1.1.15.23.15.36V14a.5.5 0 01-.5.5H6a.5.5 0 01-.5-.5z"/></svg>`
};
export const viSippy: {
  name: 'sippy';
  data: string;
} = {
  name: 'sippy',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.2 4.96l1.1-1.06A2.28 2.28 0 0010.07.67l-4.3 4.3h6.43zm3.46 4.64l-5.73 5.73a2.28 2.28 0 11-3.22-3.22l5.73-5.72a2.28 2.28 0 013.22 3.22zM11.9 5.85l-4.42 4.43H5.95a2.28 2.28 0 110-4.56h6.1l-.15.13z"/></svg>`
};
export const viSmartphoneDivert: {
  name: 'smartphone_divert';
  data: string;
} = {
  name: 'smartphone_divert',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 1.5H3a.5.5 0 00-.5.5v12c0 .28.22.5.5.5h7a.5.5 0 00.5-.5v-3.72H12V14a2 2 0 01-2 2H3a2 2 0 01-2-2V2c0-1.1.9-2 2-2h7a2 2 0 012 2v3.78h-1.5V2a.5.5 0 00-.5-.5z"/><path d="M14 3.53c.3-.3.77-.3 1.06 0l3.8 3.8a1 1 0 010 1.4l-3.8 3.8A.75.75 0 0114 11.47l2.69-2.69H9.25a.75.75 0 010-1.5h7.44L14 4.59a.75.75 0 010-1.06zM7 13.5H6A.75.75 0 016 12h1a.75.75 0 010 1.5z"/></svg>`
};
export const viSmartphone: {
  name: 'smartphone';
  data: string;
} = {
  name: 'smartphone',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M9.5 13.5h1a.75.75 0 000-1.5h-1a.75.75 0 000 1.5z"/><path fill-rule="evenodd" d="M4.5 2c0-1.1.9-2 2-2h7a2 2 0 012 2v12a2 2 0 01-2 2h-7a2 2 0 01-2-2V2zm2-.5A.5.5 0 006 2v12c0 .28.22.5.5.5h7a.5.5 0 00.5-.5V2a.5.5 0 00-.5-.5h-7z"/></svg>`
};
export const viSoundWave: {
  name: 'sound_wave';
  data: string;
} = {
  name: 'sound_wave',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 16a.75.75 0 01-.75-.75V.75a.75.75 0 011.5 0v14.5c0 .41-.34.75-.75.75zm3-3a.75.75 0 01-.75-.75v-8.5a.75.75 0 011.5 0v8.5c0 .41-.34.75-.75.75zm2.25-3.75a.75.75 0 001.5 0v-2.5a.75.75 0 00-1.5 0v2.5zM19 9a.75.75 0 01-.75-.75v-.5a.75.75 0 011.5 0v.5c0 .41-.34.75-.75.75zM.25 8.25a.75.75 0 001.5 0v-.5a.75.75 0 00-1.5 0v.5zM4 14a.75.75 0 01-.75-.75V2.75a.75.75 0 011.5 0v10.5c0 .41-.34.75-.75.75zm2.25-2.75a.75.75 0 001.5 0v-6.5a.75.75 0 00-1.5 0v6.5z"/></svg>`
};
export const viSpinnerThird: {
  name: 'spinner_third';
  data: string;
} = {
  name: 'spinner_third',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 .75a.7.7 0 01.75-.72 8 8 0 016.52 11.3.7.7 0 01-1 .3.83.83 0 01-.3-1.05 6.5 6.5 0 00-5.22-9.04c-.41-.05-.75-.38-.75-.8z"/></svg>`
};
export const viSpy: {
  name: 'spy';
  data: string;
} = {
  name: 'spy',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M14.76 3.37a3.59 3.59 0 00-.9-1.5l-.45-.46a1.44 1.44 0 00-1.91-.1c-.88.7-2.12.7-3 0a1.44 1.44 0 00-1.9.1l-.46.45c-.42.42-.73.94-.9 1.5l-.77 2.56C2.36 6.3 1 6.86 1 7.5c0 1.1 4.03 2 9 2s9-.9 9-2c0-.64-1.36-1.21-3.47-1.58l-.77-2.55zM4.73 7.4l.91-.16L6.68 3.8c.1-.33.28-.63.52-.88.24-.23.6-.25.9-.09a3.9 3.9 0 003.8 0c.3-.16.66-.14.9.1.24.24.42.54.52.87l1.04 3.44.91.16a.1.1 0 010 .2c-1.42.25-3.25.4-5.27.4-2.02 0-3.85-.15-5.27-.4a.1.1 0 010-.2zm6.81 7.37a1.58 1.58 0 01-.76-.83l-.55-1.36a.24.24 0 00-.13-.14.26.26 0 00-.2 0 .24.24 0 00-.13.14l-.55 1.36a1.58 1.58 0 01-1.73.98l-1.41-.24a2 2 0 01-1.51-1.19l-.43-1a1.72 1.72 0 011.96-2.36l3.44.77a2 2 0 00.92-.01l2.91-.73a2 2 0 012.32 2.72l-.26.61a2 2 0 01-1.5 1.19l-1.42.24c-.33.05-.67 0-.97-.15zm.67-1.34h.05l1.41-.23a.5.5 0 00.38-.3l.26-.61a.5.5 0 00-.57-.68l-2.07.52.5 1.25c0 .02.02.04.04.05zM5.77 11.6a.22.22 0 00-.25.3l.43 1c.07.16.2.27.38.3l1.4.24a.09.09 0 00.1-.06l.49-1.22-2.55-.56z"/></svg>`
};
export const viTable: {
  name: 'table';
  data: string;
} = {
  name: 'table',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M16 0a2 2 0 012 2v12a2 2 0 01-2 2H4a2 2 0 01-2-2V2c0-1.1.9-2 2-2h12zm-5.25 1.5v3.25h5.75V2a.5.5 0 00-.5-.5h-5.25zm0 13H16a.5.5 0 00.5-.5v-2.75h-5.75v3.25zm-1.5-3.25H3.5V14c0 .28.22.5.5.5h5.25v-3.25zm1.5-1.5h5.75v-3.5h-5.75v3.5zm-1.5-3.5H3.5v3.5h5.75v-3.5zm0-1.5V1.5H4a.5.5 0 00-.5.5v2.75h5.75z"/></svg>`
};
export const viTimetable: {
  name: 'timetable';
  data: string;
} = {
  name: 'timetable',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.75 1.5H15c.28 0 .5.22.5.5v2.67c.53.13 1.03.32 1.5.56V2a2 2 0 00-2-2H3a2 2 0 00-2 2v12c0 1.1.9 2 2 2h6.85a6.53 6.53 0 01-1.6-1.97v.47H3a.5.5 0 01-.5-.5v-2.75h5a6.6 6.6 0 01.12-1.5H2.5v-3.5h5.75v1.72a6.52 6.52 0 013.96-3.22H9.75V1.5zm-1.5 3.25H2.5V2c0-.28.22-.5.5-.5h5.25v3.25z"/><path d="M13.25 10.8V9.24a.75.75 0 011.5 0v1.44l.25.25A.75.75 0 0113.94 12l-.32-.32a1.25 1.25 0 01-.37-.89z"/><path fill-rule="evenodd" d="M14 16a5 5 0 100-10 5 5 0 000 10zm0-1.5a3.5 3.5 0 110-7 3.5 3.5 0 010 7z"/></svg>`
};
export const viTrash: {
  name: 'trash';
  data: string;
} = {
  name: 'trash',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M7.5 12.5v-6c0-.28.22-.5.5-.5h.5c.28 0 .5.22.5.5v6a.5.5 0 01-.5.5H8a.5.5 0 01-.5-.5zm3.5-6v6c0 .28.22.5.5.5h.5a.5.5 0 00.5-.5v-6A.5.5 0 0012 6h-.5a.5.5 0 00-.5.5z"/><path fill-rule="evenodd" d="M7 3V2c0-1.1.9-2 2-2h2a2 2 0 012 2v1h3.25a.75.75 0 010 1.5H16V14a2 2 0 01-2 2H6a2 2 0 01-2-2V4.5h-.25a.75.75 0 010-1.5H7zm1.5 0h3V2a.5.5 0 00-.5-.5H9a.5.5 0 00-.5.5v1zm-3 11c0 .28.22.5.5.5h8a.5.5 0 00.5-.5V4.5h-9V14z"/></svg>`
};
export const viTriangleWarning: {
  name: 'triangle_warning';
  data: string;
} = {
  name: 'triangle_warning',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11 11.5a1 1 0 11-2 0 1 1 0 012 0zM10.75 9V6.5a.75.75 0 00-1.5 0V9a.75.75 0 001.5 0z"/><path fill-rule="evenodd" d="M10.87 1.54l6.78 11.97a1 1 0 01-.87 1.49H3.22a1 1 0 01-.87-1.5L9.13 1.55a1 1 0 011.74 0zM10 3.04L4.07 13.5h11.86L10 3.04z"/></svg>`
};
export const viUnlock: {
  name: 'unlock';
  data: string;
} = {
  name: 'unlock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10.75 10.25a1.25 1.25 0 10-1.5 0v2a.75.75 0 001.5 0v-2z"/><path fill-rule="evenodd" d="M11.5 3v.5H13V3a3 3 0 10-6 0v2H5a2 2 0 00-2 2v7c0 1.1.9 2 2 2h10a2 2 0 002-2V7a2 2 0 00-2-2H8.5V3a1.5 1.5 0 113 0zm-7 4c0-.28.22-.5.5-.5h10c.28 0 .5.22.5.5v7a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V7z"/></svg>`
};
export const viUserGear: {
  name: 'user_gear';
  data: string;
} = {
  name: 'user_gear',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.69 3.75a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0z"/><path d="M2.93 11.3c.33-.4.8-.68 1.35-.76 1.43-.2 2.87-.29 4.3-.25-.06-.34-.03-.7.12-1.06l.2-.44a27.9 27.9 0 00-4.83.26c-.93.13-1.73.6-2.3 1.28-.75.92-.49 2.27.33 3.14a7.98 7.98 0 008.03 2.23c-.23-.13-.44-.3-.62-.52a6.02 6.02 0 01-.4-.59v-.01L9 14.4a6.55 6.55 0 01-5.82-1.97 1.4 1.4 0 01-.36-.72.59.59 0 01.1-.43z"/><path fill-rule="evenodd" d="M10.09 13.2c.07.17.14.32.23.48l.08.14c.09.15.19.3.3.44.14.18.4.22.6.1l.23-.13a.55.55 0 01.6.05c.24.18.5.33.78.45.2.09.35.28.35.5v.26c0 .23.16.44.39.47a4.54 4.54 0 001.21 0c.23-.03.4-.24.4-.47v-.26c0-.22.14-.41.35-.5.27-.12.53-.27.77-.45a.55.55 0 01.6-.05l.23.13c.2.12.46.08.6-.1.11-.14.21-.29.3-.44l.09-.14c.08-.16.16-.31.22-.48a.46.46 0 00-.2-.57l-.24-.13a.55.55 0 01-.25-.55 3.54 3.54 0 000-.9.55.55 0 01.25-.55l.23-.13c.2-.12.3-.36.21-.57a4.49 4.49 0 00-.22-.48l-.09-.14c-.09-.15-.19-.3-.3-.44a.47.47 0 00-.6-.1l-.23.13a.55.55 0 01-.6-.05 3.5 3.5 0 00-.77-.45.55.55 0 01-.35-.5v-.26a.46.46 0 00-.4-.47 4.54 4.54 0 00-1.21 0 .46.46 0 00-.4.47v.26c0 .22-.14.41-.34.5a3.5 3.5 0 00-.77.45.55.55 0 01-.61.05l-.23-.13a.47.47 0 00-.6.1c-.11.14-.21.29-.3.44l-.08.14c-.09.16-.16.31-.23.48-.09.21 0 .45.21.57l.23.13c.19.11.28.34.25.55a3.54 3.54 0 000 .9.55.55 0 01-.25.55l-.23.13c-.2.12-.3.36-.21.57zm2.17-1.7a2 2 0 114 0 2 2 0 01-4 0z"/></svg>`
};
export const viUserHeadset: {
  name: 'user_headset';
  data: string;
} = {
  name: 'user_headset',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.07 11.72c2.6-.3 5.25-.3 7.86 0 .69.08 1.23.35 1.56.66a.82.82 0 01-.27.37A8.17 8.17 0 0110 14.5c-2.12 0-3.97-.7-5.22-1.75a.82.82 0 01-.27-.37c.33-.31.87-.58 1.56-.66zm9.44.69zM3.48 11.29c-.8.76-.53 1.88.34 2.6A9.66 9.66 0 0010 16a9.6 9.6 0 006.18-2.1c.87-.73 1.15-1.85.34-2.6a4.2 4.2 0 00-2.42-1.07c-2.72-.3-5.48-.3-8.2 0-.98.1-1.83.5-2.42 1.06z"/><path d="M14 6v-.5a4 4 0 00-7.93-.75c-.08.41-.4.75-.82.75-.41 0-.76-.34-.7-.75a5.5 5.5 0 0110.95.75V6a3 3 0 01-3 3h-1.87a1 1 0 01-.13 0h-1a1 1 0 110-2h1c.37 0 .7.2.87.5h1.13c.83 0 1.5-.67 1.5-1.5z"/><path d="M11.34 6.18a1.5 1.5 0 10-2.67 0 2 2 0 00-1.05 1.14 3 3 0 115.27-1 .5.5 0 01-.39.18h-.68a2 2 0 00-.48-.32z"/></svg>`
};
export const viUserList: {
  name: 'user_list';
  data: string;
} = {
  name: 'user_list',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.69 3.75a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0z"/><path d="M2.93 11.3c.33-.4.8-.68 1.35-.76 1.48-.21 2.98-.3 4.47-.25a2.24 2.24 0 01-.2-1.5c-1.5-.04-3 .05-4.48.26-.93.13-1.73.6-2.3 1.28-.75.92-.49 2.27.33 3.14a7.98 7.98 0 006.52 2.5 2.25 2.25 0 01.02-1.5 6.58 6.58 0 01-5.45-2.03 1.4 1.4 0 01-.36-.72.59.59 0 01.1-.43zm7.82 3.2a.75.75 0 000 1.5h7.5a.75.75 0 000-1.5h-7.5zM10 12.25c0-.41.34-.75.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zm.75-3.75a.75.75 0 000 1.5h7.5a.75.75 0 000-1.5h-7.5z"/></svg>`
};
export const viUserLock: {
  name: 'user_lock';
  data: string;
} = {
  name: 'user_lock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.69 3.75a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0z"/><path d="M2.93 11.3c.33-.4.8-.68 1.35-.76 1.42-.2 2.86-.29 4.3-.25.1-.55.35-1.06.69-1.48-1.74-.08-3.48 0-5.2.24-.93.13-1.73.6-2.3 1.28-.75.92-.49 2.27.33 3.14a7.98 7.98 0 006.97 2.45 3.48 3.48 0 01-.54-1.45l-.6.03a6.48 6.48 0 01-4.74-2.06 1.4 1.4 0 01-.36-.72.59.59 0 01.1-.43zm12.32 1.2a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"/><path fill-rule="evenodd" d="M17 9a2 2 0 012 2v3a2 2 0 01-2 2h-5a2 2 0 01-2-2v-3c0-1.1.9-2 2-2v-.5a2.5 2.5 0 015 0V9zm-1.5 0v-.5a1 1 0 10-2 0V9h2zm-4 2v3c0 .28.22.5.5.5h5a.5.5 0 00.5-.5v-3a.5.5 0 00-.5-.5h-5a.5.5 0 00-.5.5z"/></svg>`
};
export const viUserPlus: {
  name: 'user_plus';
  data: string;
} = {
  name: 'user_plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.69 3.75a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0z"/><path d="M2.93 11.3c.33-.4.8-.68 1.35-.76 1.3-.19 2.62-.28 3.94-.26A2.25 2.25 0 0110.25 9h1.17c-2.44-.31-4.91-.3-7.35.05-.93.13-1.73.6-2.3 1.28-.75.92-.49 2.27.33 3.14a7.98 7.98 0 009.9 1.42V13.5h-.6a6.47 6.47 0 01-8.2-1.06 1.28 1.28 0 01-.37-.72.59.59 0 01.1-.43z"/><path d="M15 7.25v3.25h3.25a.75.75 0 010 1.5H15v3.25a.75.75 0 01-1.5 0V12h-3.25a.75.75 0 010-1.5h3.25V7.25a.75.75 0 011.5 0z"/></svg>`
};
export const viUser: {
  name: 'user';
  data: string;
} = {
  name: 'user',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M13.69 3.75a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0zM4.1 13.47c-.82-.87-1.08-2.22-.32-3.14a3.64 3.64 0 012.29-1.28c2.56-.36 5.17-.36 7.74 0 .92.13 1.72.6 2.28 1.28.77.92.5 2.27-.31 3.14a7.98 7.98 0 01-11.68 0zm.83-2.18a.59.59 0 00-.1.43c.03.23.15.5.36.72a6.48 6.48 0 009.5 0c.2-.22.32-.49.35-.72.03-.2-.02-.34-.1-.43-.33-.4-.8-.67-1.35-.75a25.85 25.85 0 00-7.3 0c-.55.08-1.03.35-1.36.75z"/></svg>`
};
export const viUsers: {
  name: 'users';
  data: string;
} = {
  name: 'users',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.94 7.5a3.75 3.75 0 100-7.5 3.75 3.75 0 000 7.5zm0-1.5a2.25 2.25 0 110-4.5 2.25 2.25 0 010 4.5zm-6.16 4.33c-.76.92-.5 2.27.32 3.14a7.98 7.98 0 0011.68 0c.81-.87 1.08-2.22.31-3.14a3.64 3.64 0 00-2.28-1.28 27.35 27.35 0 00-7.74 0c-.93.13-1.73.6-2.3 1.28zm2.5.2c2.43-.34 4.89-.34 7.31 0 .55.09 1.02.36 1.35.76.08.1.13.22.1.43-.03.23-.15.5-.36.72a6.48 6.48 0 01-9.49 0 1.4 1.4 0 01-.36-.72.59.59 0 01.1-.43c.33-.4.8-.67 1.35-.75zM2.25 6.5a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5zm0-1.5a.75.75 0 110-1.5.75.75 0 010 1.5z"/><path d="M4.48 7.25c.29 0 .52.23.52.52-.66.2-1.25.55-1.76.98h-.49c-.69 0-1.25.56-1.25 1.25v1.25a.75.75 0 01-1.5 0V10a2.75 2.75 0 012.75-2.75h1.73zm12.77 1.5h-.62A5.14 5.14 0 0015 7.81c0-.31.25-.56.56-.56h1.69A2.75 2.75 0 0120 10v1.25a.75.75 0 01-1.5 0V10c0-.69-.56-1.25-1.25-1.25z"/><path fill-rule="evenodd" d="M17.75 6.5a2.25 2.25 0 110-4.5 2.25 2.25 0 010 4.5zm0-1.5a.75.75 0 100-1.5.75.75 0 000 1.5z"/></svg>`
};
export const viValkyrie: {
  name: 'valkyrie';
  data: string;
} = {
  name: 'valkyrie',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M14.06 2.58l3.25-1.3a.5.5 0 01.69.46v1.61c0 .31-.19.59-.47.7l-5 2 1.53-3.47zM8.7 14.72l4.83-1.93a.75.75 0 00.47-.7v-1.41a.5.5 0 00-.69-.47l-3.18 1.28-1.42 3.23zm3.25-7.36L15.31 6a.5.5 0 01.69.47v1.07c0 .31-.19.59-.47.7l-4.82 1.93 1.24-2.82zM2.32 3.7a.5.5 0 01.46-.7H4c.3 0 .57.18.68.45L7.5 10l2.8-6.55A.75.75 0 0111 3h2L7.73 14.5c-.1.2-.37.2-.46 0L2.32 3.7z"/></svg>`
};
export const viVideoRecorder: {
  name: 'video_recorder';
  data: string;
} = {
  name: 'video_recorder',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M1 4c0-1.1.9-2 2-2h8a2 2 0 012 2v8a2 2 0 01-2 2H3a2 2 0 01-2-2V4zm2-.5a.5.5 0 00-.5.5v8c0 .28.22.5.5.5h8a.5.5 0 00.5-.5V4a.5.5 0 00-.5-.5H3z"/><path d="M17.53 13.22L14.5 11.6V9.9l3 1.6v-7l-3 1.6V4.4l3.03-1.62a1 1 0 011.47.89v8.66a1 1 0 01-1.47.89z"/></svg>`
};
export const viVoiceRecorder: {
  name: 'voice_recorder';
  data: string;
} = {
  name: 'voice_recorder',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 0a3 3 0 00-3 3v3.5a3 3 0 006 0V3a3 3 0 00-3-3zm1.5 6.5a1.5 1.5 0 01-3 0V3a1.5 1.5 0 113 0v3.5z"/><path d="M10.75 12.45A6 6 0 0016 6.5a.5.5 0 00-.5-.5H15a.5.5 0 00-.5.5 4.5 4.5 0 11-9 0A.5.5 0 005 6h-.5a.5.5 0 00-.5.5 6 6 0 005.25 5.95v2.05h-1.5a.75.75 0 000 1.5h4.5a.75.75 0 000-1.5h-1.5v-2.05z"/></svg>`
};
export const viVoicemail: {
  name: 'voicemail';
  data: string;
} = {
  name: 'voicemail',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M7.12 10.5A4 4 0 104 12h12a4 4 0 10-3.12-1.5H7.12zM4 10.5a2.5 2.5 0 110-5 2.5 2.5 0 010 5zm12 0a2.5 2.5 0 110-5 2.5 2.5 0 010 5z"/></svg>`
};
export const viWallpaper: {
  name: 'wallpaper';
  data: string;
} = {
  name: 'wallpaper',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M8.87 5.31l5.2 5.19h-2.13L7.8 6.37a1.25 1.25 0 00-1.72-.04L3.5 8.66V6.64l1.59-1.43a2.75 2.75 0 013.78.1zM13.5 7a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"/><path fill-rule="evenodd" d="M1 2c0-1.1.9-2 2-2h14a2 2 0 012 2v9a2 2 0 01-2 2h-6.25v1.5h2a.75.75 0 010 1.5h-5.5a.75.75 0 010-1.5h2V13H3a2 2 0 01-2-2V2zm2-.5a.5.5 0 00-.5.5v9c0 .28.22.5.5.5h14a.5.5 0 00.5-.5V2a.5.5 0 00-.5-.5H3z"/></svg>`
};
export const viXMark: {
  name: 'x_mark';
  data: string;
} = {
  name: 'x_mark',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 9.06l3.89 3.89a.75.75 0 001.06-1.06L11.06 8l3.89-3.89a.75.75 0 10-1.06-1.06L10 6.94 6.11 3.05a.75.75 0 00-1.06 1.06L8.94 8l-3.89 3.89a.75.75 0 101.06 1.06L10 9.06z"/></svg>`
};
export type Valkyrie =
  | 'angle_down'
  | 'angle_left'
  | 'angle_right'
  | 'angle_up'
  | 'apple_app_store'
  | 'arrow_down_to_line'
  | 'arrow_down'
  | 'arrow_left_from_bracket'
  | 'arrow_left_to_bracket'
  | 'arrow_left_to_line'
  | 'arrow_left'
  | 'arrow_right_from_bracket'
  | 'arrow_right_to_bracket'
  | 'arrow_right_to_line'
  | 'arrow_right'
  | 'arrow_up_to_line'
  | 'arrow_up'
  | 'bars'
  | 'blf'
  | 'book'
  | 'box_full'
  | 'building'
  | 'calendar_holidays'
  | 'calendar'
  | 'check'
  | 'circle_check'
  | 'circle_danger'
  | 'circle_info'
  | 'circle_plus'
  | 'circle_question'
  | 'circle_user'
  | 'circle_warning'
  | 'clock'
  | 'compass'
  | 'copy'
  | 'dashboard'
  | 'desk_phone'
  | 'desktop'
  | 'devices'
  | 'earth'
  | 'ellipsis'
  | 'envelope'
  | 'euro'
  | 'facebook_messenger'
  | 'facebook'
  | 'fax'
  | 'fingerprint'
  | 'flag_checkered'
  | 'flag'
  | 'floppy_disk'
  | 'folder'
  | 'gauge'
  | 'gear'
  | 'google_play'
  | 'headset'
  | 'heart_broken'
  | 'heart_half'
  | 'heart'
  | 'history'
  | 'home'
  | 'id_card'
  | 'image'
  | 'laptop'
  | 'layers_plus'
  | 'layers'
  | 'lightbulb_on'
  | 'lightbulb'
  | 'linkedin'
  | 'list_ol'
  | 'lock'
  | 'map_marker_slashed'
  | 'map_marker'
  | 'message'
  | 'network'
  | 'parachute'
  | 'pen'
  | 'phone_gear'
  | 'phone'
  | 'plus'
  | 'present'
  | 'refresh'
  | 'search'
  | 'send'
  | 'server'
  | 'shield_danger'
  | 'shield_keyhole'
  | 'shield_plus'
  | 'shield'
  | 'sim_card'
  | 'sippy'
  | 'smartphone_divert'
  | 'smartphone'
  | 'sound_wave'
  | 'spinner_third'
  | 'spy'
  | 'table'
  | 'timetable'
  | 'trash'
  | 'triangle_warning'
  | 'unlock'
  | 'user_gear'
  | 'user_headset'
  | 'user_list'
  | 'user_lock'
  | 'user_plus'
  | 'user'
  | 'users'
  | 'valkyrie'
  | 'video_recorder'
  | 'voice_recorder'
  | 'voicemail'
  | 'wallpaper'
  | 'x_mark';
export interface ValkyrieIcon {
  name: Valkyrie;
  data: string;
}
export type ValkyrieIconNameSubset<
  T extends Readonly<ValkyrieIcon[]>
> = T[number]['name'];
