name: Deploy to GitHub Pages

on:
  push:
    branches: ["1.0"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: valkyrie
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.1.3
      - name: Set up Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "pnpm"
          cache-dependency-path: valkyrie/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Production build
        run: pnpm prod
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: valkyrieicons
          path: |
            valkyrie/dist
            valkyrie/node_modules

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.1.3
      - name: Set up Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v8
        with:
          name: valkyrieicons
      - name: Install dependencies
        if: steps.download.outcome == 'success'
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
